# -*- coding: utf-8 -*-

import re
import urllib.parse
from flask import Flask, request, render_template
from bs4 import BeautifulSoup

from versionsDB import versions_search
from albumDB import album
from biographyDB import biography
from groupsDB import groups
from tracksDB import tracks
from membersDB import members
from nbenies_articlesDB import articles

lists = []
lists.append('I-#Idim-IIm7-#IIdim-IIIm7')
lists.append('I-#Idim-IIm7-V7')
lists.append('I-I+-IV-#IVdim')
lists.append('I-I7-IV-#IVdim')
lists.append('I-I7-IV-IVm')
lists.append('I-IIm7-IIIm7-IIm7')
lists.append('I-IIm7-IIIm7-bIIIdim')
lists.append('I-III7-IImin')
lists.append('I-III7-IV-II7-V7')
lists.append('I-III7-IV')
lists.append('I-III7-VI7-II7-V7')
lists.append('I-III7-VI7-II7-IIm')
lists.append('I-III7-VI7-II7-IVm')
lists.append('I-III7-VIm-II7')
lists.append('I-IIIm7b5-VI7')
lists.append('I-IV7')
lists.append('I-IVm')
lists.append('I-VI7-II7-V7')
lists.append('I-VI7-IIm7-V7')
lists.append('I-VI7-IV-IVm')
lists.append('I-VI7-VIIm7b5-III7')
lists.append('I-VIm7-IIm7-V7')
lists.append('I-VII7-I')
lists.append('I-VII7-III7-VI7-II7-V7')
lists.append('I-bVII7-VI7')
lists.append('I-bVII7-VI7-II7-V7')
lists.append('I-IV')
lists.append('I-Im7')
lists.append('I-Im')
lists.append('I-II7b5')
lists.append('I-VIm7-IIIm7')
lists.append('Im')
lists.append('I7-IV')
lists.append('I7-IV-III7-VIm-II7')
lists.append('I7-IV-VI7-IIm')
lists.append('I7-IV7-bVII7-bIII7-V7')
lists.append('I7-IVm')
lists.append('I7-VII7-bVII7-VI7')
lists.append('I7+')
lists.append('II')
lists.append('IIm')
lists.append('IIm-VIm')
lists.append('IIm7-V7-downinwholesteps')
lists.append('IIm7-Vm7')
lists.append('IIm7b5-V7')
lists.append('II7')
lists.append('II7-V7')
lists.append('II7-bII7-I')
lists.append('III')
lists.append('IIIm')
lists.append('IIIm7-VI7-II7-IIm7-V7')
lists.append('IIIm7-VI7-IIm7-V7')
lists.append('IIIm7-bIII7-IIm7-bII7-I')
lists.append('IIIm7-bIIIm7-IIm7-V7')
lists.append('IIIm7b5-VI7')
lists.append('IIIm7b5-VI7-IIm7b5-V7')
lists.append('IIIm7b5-VI7-IIm-IIm7-V7')
lists.append('IIIm7b5-VI7-IV-IVm')
lists.append('III7-IV-IVm')
lists.append('III7-VI7-II7-V7')
lists.append('IV')
lists.append('IV-#IVdim-I')
lists.append('IV-IVm')
lists.append('IV-bVI')
lists.append('IVm')
lists.append('IVm6')
lists.append('IV7')
lists.append('IV7-III7-VI7-II7')
lists.append('V')
lists.append('V-VI')
lists.append('Vm')
lists.append('Vm7')
lists.append('V7+')
lists.append('V7sus')
lists.append('VI')
lists.append('VI-V')
lists.append('VIm')
lists.append('VIm-IIm')
lists.append('VIm-II7')
lists.append('VIm-III')
lists.append('VIm-IIIm')
lists.append('VI7-IIm')
lists.append('VI7-II7-V7-I')
lists.append('VI7-IV-IVm')
lists.append('VI7-IV')
lists.append('VII')
lists.append('VII-I')
lists.append('VIIm')
lists.append('VIIm7b5-III7-VIm7-II7I')
lists.append('VII7')
lists.append('VII7-III7-VI7-II7-V7')
lists.append('bII')
lists.append('bIIm')
lists.append('bII7')
lists.append('bII7-bVI7-V7')
lists.append('bIII')
lists.append('bIII-bVI-bII')
lists.append('bIIIm')
lists.append('bIII7')
lists.append('bIIIdim')
lists.append('bV')
lists.append('bVI')
lists.append('bVI-bV')
lists.append('bVI7')
lists.append('bVI7-V7')
lists.append('bVII')
lists.append('bVIIm')
lists.append('bVII7-VI7')
lists.append('bVII7-VI7-II7')
lists.append('bVII7-VI7-II7-V7')
lists.append('bVII7-VI7-IIm')
lists.append('bVII7-VI7-bVI7-V7')
lists.append('start_IV')
lists.append('start_IV-IVm')
lists.append('start_II7')
lists.append('start_bVI7-V7')
lists.append('start_VIm-VIm/maj7-VIm7-VIm6')
lists.append('start_VIm7')
lists.append('IIm7-V7_down_in_half_steps')
lists.append('A_section_IIm7-V7')
lists.append('I')
lists.append('Im')
lists.append('I7-VII7-bVII7-VI7')
lists.append('II')
lists.append('IIm')
lists.append('III')
lists.append('IIIm')
lists.append('III7-VI7-II7-V7')
lists.append('IV')
lists.append('IV-I')
lists.append('IV-IIm')
lists.append('IV-III7-VI7-II7-V7')
lists.append('IV-III')
lists.append('IV-IVm')
lists.append('IV-V_or_IV-II7-V7')
lists.append('IV-bIII')
lists.append('IV-bVI')
lists.append('IV-#IVdim-I')
lists.append('IVm')
lists.append('IV7')
lists.append('V')
lists.append('V-VI')
lists.append('Vm')
lists.append('VI7-II7-V7')
lists.append('VI')
lists.append('VIm')
lists.append('VIm-IIm')
lists.append('VII')
lists.append('VIIm')
lists.append('bII')
lists.append('bII7')
lists.append('bIII')
lists.append('bIII7')
lists.append('bV')
lists.append('bVI')
lists.append('bVI-bV')
lists.append('bVI7')
lists.append('bVII')
lists.append('bVII-bV')
lists.append('5th_cycle')
lists.append('V7_down_chroma')
lists.append('IIm7-V7_down_whole_steps')
lists.append('IIm7b5-V7_down_whole_steps')

list_titles = []
list_titles.append('A PORTRAIT OF JENNIE')
list_titles.append('A FOGGY DAY')
list_titles.append('AFTER YOU\'VE GONE')
list_titles.append('AIN\'T MISBEHAVIN')
list_titles.append('AIREGIN')
list_titles.append('AIR MAIL SPECIAL')
list_titles.append('ALEXANDER\'S RAGTIME BAND')
list_titles.append('ALL BLUES')
list_titles.append('ALL GOD\'S CHILDREN GOT RHYTHM')
list_titles.append('ALL OF ME')
list_titles.append('ALL OF YOU')
list_titles.append('ALL THE THINGS YOU ARE')
list_titles.append('ALMOST LIKE BEING IN LOVE')
list_titles.append('ALONE TOGETHER')
list_titles.append('ALONG CAME BETTY')
list_titles.append('ALWAYS')
list_titles.append('AMAZING GRACE')
list_titles.append('AM I BLUE')
list_titles.append('ANGEL EYES')
list_titles.append('ANYTHING GOES')
list_titles.append('APRIL IN PARIS')
list_titles.append('AREN\'T YOU GLAD YOU\'RE YOU')
list_titles.append('AS LONG AS I LIVE')
list_titles.append('AS TIME GOES BY')
list_titles.append('AT SUNDOWN')
list_titles.append('AUTUMN IN NEW YORK')
list_titles.append('AUTUMN LEAVES')
list_titles.append('AVALON')
list_titles.append('AZURE')
list_titles.append('BASIN STREET BLUES')
list_titles.append('BAUBLES BANGLES AND BEADS')
list_titles.append('BEAUTIFUL LOVE')
list_titles.append('BERNIE\'S TUNE')
list_titles.append('BETWEEN THE DEVIL AND THE DEEP BLUE SEA')
list_titles.append('BEWITCHED BOTHERED AND BEWILDERED')
list_titles.append('BIDIN MY TIME')
list_titles.append('BILL BAILEY')
list_titles.append('BIRTH OF THE BLUES')
list_titles.append('BLACK AND BLUE')
list_titles.append('BLACK COFFEE')
list_titles.append('BLUE BOSSA')
list_titles.append('BLUE LOU')
list_titles.append('BLUE MONK ')
list_titles.append('BLUE MOON')
list_titles.append('BLUE ROOM (THE)')
list_titles.append('BLUESETTE')
list_titles.append('BLUE SKIES')
list_titles.append('BODY AND SOUL')
list_titles.append('BORN TO BE BLUE')
list_titles.append('BROADWAY')
list_titles.append('BUT BEAUTIFUL')
list_titles.append('BUT NOT FOR ME')
list_titles.append('BYE BYE BLACKBIRD')
list_titles.append('BYE BYE BLUES')
list_titles.append('BY MYSELF')
list_titles.append('CABIN IN THE SKY')
list_titles.append('CAN\'T GET OUT OF THIS MOOD')
list_titles.append('CAN\'T HELP LOVIN DAT MAN')
list_titles.append('CAN\'T WE BE FRIENDS')
list_titles.append('CARAVAN')
list_titles.append('CARNIVAL (BLACK ORPHEUS)')
list_titles.append('CHEEK TO CHEEK')
list_titles.append('CHELSEA BRIDGE')
list_titles.append('CHEROKEE')
list_titles.append('CHICAGO')
list_titles.append('CHRISTMAS SONG')
list_titles.append('COME RAIN OR COME SHINE')
list_titles.append('COMES LOVE')
list_titles.append('CONFIRMATION')
list_titles.append('CORCOVADO')
list_titles.append('COTTAGE FOR SALE')
list_titles.append('COTTON TAIL')
list_titles.append('CRAZY RHYTHM')
list_titles.append('CRY ME A RIVER')
list_titles.append('CUTE')
list_titles.append('DANCING IN THE DARK')
list_titles.append('DANCING ON THE CEILING')
list_titles.append('DANNY BOY')
list_titles.append('DARN THAT DREAM')
list_titles.append('DAY BY DAY')
list_titles.append('DAY IN  DAY OUT')
list_titles.append('DAYS OF WINE AND ROSES')
list_titles.append('DEARLY BELOVED')
list_titles.append('DEED I DO')
list_titles.append('DEEP PURPLE')
list_titles.append('DESAFINADA')
list_titles.append('DJANGO')
list_titles.append('DO NOTHIN TILL YOU HEAR FROM ME')
list_titles.append('DON\'T BLAME ME')
list_titles.append('DON\'T GET AROUND MUCH ANY MORE')
list_titles.append('DON\'T TAKE YOUR LOVE FROM ME')
list_titles.append('DOXY')
list_titles.append('EAST OF THE SUN')
list_titles.append('EASY LIVIN')
list_titles.append('EASY TO LOVE')
list_titles.append('EMBRACEABLE YOU')
list_titles.append('EPISTROPHY')
list_titles.append('EVERYTHING HAPPENS TO ME')
list_titles.append('EVERYTHING I\'VE GOT BELONGS TO YOU')
list_titles.append('EVERY TIME WE SAY GOODBYE')
list_titles.append('EXACTLY LIKE YOU')
list_titles.append('FALLING IN LOVE WITH LOVE')
list_titles.append('FASCINATING RHYTHM')
list_titles.append('FINE AND DANDY')
list_titles.append('FINE ROMANCE (A)')
list_titles.append('FLY ME TO THE MOON')
list_titles.append('FOLKS WHO LIVE ON THE HILL')
list_titles.append('FOOLS RUSH IN')
list_titles.append('FOR ALL WE KNOW')
list_titles.append('FOUR')
list_titles.append('FREDDIE THE FREELOADER')
list_titles.append('FROM THIS MOMENT ON')
list_titles.append('GAL IN CALICO')
list_titles.append('GEE BABY AIN\'T I GOOD TO YOU')
list_titles.append('GEORGIA ON MY MIND')
list_titles.append('GET HAPPY')
list_titles.append('GET OUT OF TOWN')
list_titles.append('GHOST OF A CHANCE WITH YOU')
list_titles.append('GIANT STEPS')
list_titles.append('GIRL FROM IPANEMA')
list_titles.append('GIVE ME THE SIMPLE LIFE')
list_titles.append('GLAD TO BE UNHAPPY')
list_titles.append('GOD BLESS THE CHILD')
list_titles.append('GONE WITH THE WIND')
list_titles.append('GREEN DOLPHIN STREET')
list_titles.append('GROOVIN HIGH')
list_titles.append('HALLELUJAH')
list_titles.append('HAVE YOU MET MISS JONES')
list_titles.append('HEAT WAVE')
list_titles.append('HERE\'S THAT RAINY DAY')
list_titles.append('HONEYSUCKLE ROSE')
list_titles.append('HOW ABOUT YOU')
list_titles.append('HOW DEEP IS THE OCEAN')
list_titles.append('HOW HIGH THE MOON')
list_titles.append('HOW INSENSITIVE')
list_titles.append('HOW LONG HAS THIS BEEN GOING ON')
list_titles.append('I CAN\'T BELIEVE THAT YOUR IN LOVE')
list_titles.append('I CAN\'T GET STARTED WITH YOU')
list_titles.append('I CAN\'T GIVE YOU ANYTHING BUT LOVE')
list_titles.append('I CONCENTRATE ON YOU')
list_titles.append('I COULD WRITE A BOOK')
list_titles.append('I COVER THE WATERFRONT')
list_titles.append('IDAHO')
list_titles.append('I DIDN\'T KNOW WHAT TIME IT WAS')
list_titles.append('I DON\'T KNOW WHY')
list_titles.append('I FALL IN LOVE TOO EASILY')
list_titles.append('IF I HAD YOU')
list_titles.append('IF I LOVE AGAIN')
list_titles.append('IF I SHOULD LOSE YOU')
list_titles.append('IF I WERE A BELL')
list_titles.append('I FOUND A NEW BABY')
list_titles.append('IF THERE IS SOMEONE LOVELIER')
list_titles.append('IF YOU COULD SEE ME NOW')
list_titles.append('I GET A KICK OUT OF YOU')
list_titles.append('I GOT IT BAD')
list_titles.append('I GOT RHYTHM')
list_titles.append('I HADN\'T ANYONE \'TIL YOU')
list_titles.append('I HEAR A RHAPSODY')
list_titles.append('I HEAR MUSIC')
list_titles.append('I LEFT MY HEART IN SAN FRANCISCO')
list_titles.append('I LET A SONG GO OUT  OF MY HEART')
list_titles.append('I\'LL BE AROUND')
list_titles.append('I\'LL BE SEEING YOU')
list_titles.append('I\'LL GET BY')
list_titles.append('I\'LL NEVER BE THE SAME')
list_titles.append('I\'LL REMEMBER APRIL')
list_titles.append('I\'LL STRING ALONG WITH YOU')
list_titles.append('I\'LL TAKE MANHATTAN')
list_titles.append('I\'LL TAKE ROMANCE')
list_titles.append('ILL WIND')
list_titles.append('I LOVE PARIS')
list_titles.append('I LOVE YOU')
list_titles.append('IMAGINATION')
list_titles.append('I MAY BE WRONG')
list_titles.append('I\'M BEGINNING TO SEE THE LIGHT')
list_titles.append('I\'M CONFESSIN')
list_titles.append('I\'M GETTIN SENTIMENTAL OVER YOU')
list_titles.append('I\'M GLAD THERE IS YOU')
list_titles.append('I\'M IN THE MOOD FOR LOVE')
list_titles.append('I\'M OLD FASHIONED')
list_titles.append('IN A MELLOW TONE')
list_titles.append('IN A SENTIMENTAL MOOD')
list_titles.append('INDIANA')
list_titles.append('INDIAN SUMMER')
list_titles.append('I NEVER KNEW')
list_titles.append('IN MY SOLITUDE')
list_titles.append('INVITATION')
list_titles.append('IN YOUR OWN SWEET WAY')
list_titles.append('I REMEMBER YOU')
list_titles.append('I SHOULD CARE')
list_titles.append('ISN\'T IT ROMANTIC')
list_titles.append('I SURRENDER DEAR')
list_titles.append('IT COULD HAPPEN TO YOU')
list_titles.append('IT DON\'T MEAN A THING')
list_titles.append('IT HAD TO BE YOU')
list_titles.append('I THOUGHT ABOUT YOU')
list_titles.append('IT MIGHT AS WELL BE SPRING')
list_titles.append('IT NEVER ENTERED MY MIND')
list_titles.append('IT\'S ALL RIGHT WITH ME')
list_titles.append('IT\'S ONLY A PAPER MOON')
list_titles.append('IT\'S THE TALK OF THE TOWN')
list_titles.append('IT\'S YOU OR NO ONE')
list_titles.append('IT WAS JUST ONE OF THOSE THINGS')
list_titles.append('I\'VE GOT A CRUSH ON YOU')
list_titles.append('I\'VE GOT MY LOVE TO KEEP ME WARM')
list_titles.append('I\'VE GOT THE WORLD ON A STRING')
list_titles.append('I\'VE GOT YOU UNDER MY SKIN')
list_titles.append('I\'VE GROWN ACCUSTOMED TO YOUR FACE')
list_titles.append('I WANT TO BE HAPPY')
list_titles.append('I WISH I WERE IN LOVE AGAIN')
list_titles.append('I WON\'T DANCE')
list_titles.append('JEEPERS  CREEPERS')
list_titles.append('JORDU')
list_titles.append('JOY SPRING')
list_titles.append('JUST FRIENDS')
list_titles.append('JUST IN TIME')
list_titles.append('JUST SQUEEZE ME')
list_titles.append('JUST YOU JUST ME')
list_titles.append('LADY BE GOOD')
list_titles.append('LADY BIRD')
list_titles.append('LADY IN RED')
list_titles.append('LADY IS A TRAMP')
list_titles.append('LAST TIME I SAW PARIS')
list_titles.append('LAURA')
list_titles.append('LAZYBIRD')
list_titles.append('LET\'S FACE THE MUSIC AND DANCE')
list_titles.append('LIKE SOMEONE IN LOVE')
list_titles.append('LIL DARLIN')
list_titles.append('LIMEHOUSE BLUES')
list_titles.append('LITTLE WHITE LIES')
list_titles.append('LIZA')
list_titles.append('LONG AGO AND FAR AWAY')
list_titles.append('LOOK FOR THE SILVER LINING')
list_titles.append('LOOKING FOR A BOY')
list_titles.append('LOVE FOR SALE')
list_titles.append('LOVE ME OR LEAVE ME')
list_titles.append('LOVE NEST (THE)')
list_titles.append('LOVER COME BACK TO ME')
list_titles.append('LOVER')
list_titles.append('LOVER MAN')
list_titles.append('LOVE WALKED IN')
list_titles.append('LULLABY IN RHYTHM')
list_titles.append('LULLABY OF BIRDLAND')
list_titles.append('LULLABY OF BROADWAY')
list_titles.append('LULLABY OF THE LEAVES')
list_titles.append('MAKIN WHOOPEE')
list_titles.append('MEAN TO ME')
list_titles.append('MEDITATION')
list_titles.append('MEMORIES OF YOU')
list_titles.append('MISTY')
list_titles.append('MOOD  INDIGO')
list_titles.append('MOONGLOW')
list_titles.append('MOONLIGHT IN VERMONT')
list_titles.append('MORE THAN YOU KNOW')
list_titles.append('MOUNTAIN GREENERY')
list_titles.append('MY BLUE HEAVEN')
list_titles.append('MY FAVORITE THINGS')
list_titles.append('MY FOOLISH HEART')
list_titles.append('MY FUNNY VALENTINE')
list_titles.append('MY HEART BELONGS TO DADDY')
list_titles.append('MY HEART STOOD STILL')
list_titles.append('MY IDEAL')
list_titles.append('MY MELANCHOLY BABY')
list_titles.append('MY OLD FLAME')
list_titles.append('MY ONE AND ONLY LOVE')
list_titles.append('MY ROMANCE')
list_titles.append('MY SHINING HOUR')
list_titles.append('MY SHIP')
list_titles.append('MY SILENT LOVE')
list_titles.append('NEARNESS OF YOU (THE)')
list_titles.append('NICE WORK IF YOU CAN GET IT')
list_titles.append('NIGHT AND DAY')
list_titles.append('NIGHT IN TUNISIA')
list_titles.append('NOBODY ELSE BUT ME')
list_titles.append('NO MOON AT ALL')
list_titles.append('OLD DEVIL MOON')
list_titles.append('ON A CLEAR DAY')
list_titles.append('ON A SLOW BOAT TO CHINA')
list_titles.append('ONCE IN A WHILE')
list_titles.append('ONE I LOVE BELONGS TO SOMEBODY')
list_titles.append('ONE NOTE SAMBA')
list_titles.append('ON THE STREET WHERE YOU LIVE')
list_titles.append('ON THE SUNNY SIDE OF THE STREET')
list_titles.append('OUR DAY WILL COME')
list_titles.append('OUR LOVE IS HERE TO STAY')
list_titles.append('OUT OF NOWHERE')
list_titles.append('OUT OF THIS WORLD')
list_titles.append('OVER THE RAINBOW')
list_titles.append('PENNIES FROM HEAVEN')
list_titles.append('PEOPLE WILL SAY WE\'RE IN LOVE')
list_titles.append('PERDIDO')
list_titles.append('PICK YOURSELF UP')
list_titles.append('POLKA DOTS AND MOONBEAMS')
list_titles.append('POOR BUTTERFLY')
list_titles.append('PRELUDE TO A KISS')
list_titles.append('QUIET NIGHTS OF QUIET STARS')
list_titles.append('RECORDAME')
list_titles.append('ROSE ROOM')
list_titles.append('ROSETTA')
list_titles.append('ROUND MIDNIGHT')
list_titles.append('RUBY MY DEAR')
list_titles.append('SAMBA DE ORFEU')
list_titles.append('SATIN DOLL')
list_titles.append('SAVOY BLUES')
list_titles.append('SCRAPPLE FROM THE APPLE')
list_titles.append('SECRET LOVE')
list_titles.append('SEPTEMBER IN THE RAIN')
list_titles.append('SEPTEMBER SONG')
list_titles.append('SEVEN COME ELEVEN')
list_titles.append('SHADOW OF YOUR SMILE')
list_titles.append('SHE\'S FUNNY THAT WAY')
list_titles.append('SHINY STOCKINGS')
list_titles.append('SKYLARK')
list_titles.append('SMOKE GETS IN YOUR EYES')
list_titles.append('SOFTLY AS IN A MORNING SUNRISE')
list_titles.append('SO IN LOVE')
list_titles.append('SOLAR')
list_titles.append('SOMEBODY LOVES ME')
list_titles.append('SOMEDAY MY PRINCE WILL COME')
list_titles.append('SOMEONE TO WATCH OVER ME')
list_titles.append('SOMETIMES I\'M HAPPY')
list_titles.append('THE SONG IS YOU')
list_titles.append('SOON')
list_titles.append('SOPHISTICATED LADY')
list_titles.append('SO WHAT')
list_titles.append('SPEAK LOW')
list_titles.append('S\'POSIN')
list_titles.append('SPRING IS HERE')
list_titles.append('STARDUST')
list_titles.append('STAR EYES')
list_titles.append('STARS FELL ON ALABAMA')
list_titles.append('STELLA BY STARLIGHT')
list_titles.append('ST JAMES INFIRMARY BLUES')
list_titles.append('ST LOUIS BLUES')
list_titles.append('STOMPIN AT THE SAVOY')
list_titles.append('STORMY WEATHER')
list_titles.append('STREET OF DREAMS')
list_titles.append('STRIKE UP THE BAND')
list_titles.append('ST THOMAS')
list_titles.append('SUGAR')
list_titles.append('SUMMERTIME')
list_titles.append('SWEET AND LOVELY')
list_titles.append('SWEET GEORGIA BROWN')
list_titles.append('SWEETHEARTS ON PARADE')
list_titles.append('SWEET LORRAINE')
list_titles.append('SWINGING ON A STAR')
list_titles.append('S\'WONDERFUL')
list_titles.append('TAKE FIVE')
list_titles.append('TAKE THE A TRAIN')
list_titles.append('TAKING A CHANCE ON LOVE')
list_titles.append('TANGERINE')
list_titles.append('TEA FOR TWO')
list_titles.append('TENDERLY')
list_titles.append('THAT OLD FEELING')
list_titles.append('THE END OF A LOVE AFFAIR')
list_titles.append('THE MAN I LOVE')
list_titles.append('THE MORE I SEE YOU')
list_titles.append('THE WAY YOU LOOK TONIGHT')
list_titles.append('THERE IS NO GREATER LOVE')
list_titles.append('THERE\'S A SMALL HOTEL')
list_titles.append('THERE WILL NEVER BE ANOTHER YOU')
list_titles.append('THESE FOOLISH THINGS')
list_titles.append('THEY ALL LAUGHED')
list_titles.append('THEY CAN\'T TAKE THAT AWAY')
list_titles.append('THINGS AIN\'T WHAT THEY USED TO BE')
list_titles.append('THIS CAN\'T BE LOVE')
list_titles.append('THIS YEARS KISSES')
list_titles.append('THOU SWELL')
list_titles.append('THREE LITTLE WORDS')
list_titles.append('TIME AFTER TIME')
list_titles.append('TOO MARVELOUS FOR WORDS')
list_titles.append('TOUCH OF YOUR LIPS (THE)')
list_titles.append('TRY A LITTLE TENDERNESS')
list_titles.append('TUNE UP')
list_titles.append('TWO SLEEPY PEOPLE')
list_titles.append('UNDECIDED')
list_titles.append('UNTIL THE REAL THING COMES ALONG')
list_titles.append('UP A LAZY RIVER')
list_titles.append('VERY THOUGHT OF YOUTHE')
list_titles.append('WAIT TILL YOU SEE HER')
list_titles.append('WAVE')
list_titles.append('WELL YOU NEEDN\'T')
list_titles.append('WHAT A DIFFERENCE A DAY MADE')
list_titles.append('WHAT A LITTLE MOONLIGHT CAN DO')
list_titles.append('WHAT IS THERE TO SAY')
list_titles.append('WHAT IS THIS THING CALLED LOVE')
list_titles.append('WHAT\'LL I DO')
list_titles.append('WHAT\'S NEW')
list_titles.append('WHEN I FALL IN LOVE')
list_titles.append('WHEN SUNNY GETS BLUE')
list_titles.append('WHEN THE SAINTS GO MARCHING IN')
list_titles.append('WHEN YOUR LOVER HAS GONE')
list_titles.append('WHEN YOU WISH UPON A STAR')
list_titles.append('WHERE OR WHEN')
list_titles.append('WHIFFENPOOF SONG')
list_titles.append('WHISPERING')
list_titles.append('WHITE CHRISTMAS')
list_titles.append('WHO CARES')
list_titles.append('WHY SHOULDN\'T I')
list_titles.append('WILLOW WEEP FOR ME')
list_titles.append('WITH THE WIND AND THE RAIN')
list_titles.append('WORLD IS WAITING FOR THE SUNRISE')
list_titles.append('WRAP YOUR TROUBLES IN DREAMS')
list_titles.append('YARDBIRD SUITE')
list_titles.append('YESTERDAY')
list_titles.append('YESTERDAYS')
list_titles.append('YOU AND THE NIGHT AND THE MUSIC')
list_titles.append('YOU BROUGHT A NEW KIND OF LOVE')
list_titles.append('YOU\'D BE SO NICE TO COME HOME TO')
list_titles.append('YOU DON\'T KNOW WHAT LOVE IS')
list_titles.append('YOU DO SOMETHING TO ME')
list_titles.append('YOU GO TO MY HEAD')
list_titles.append('YOURS IS MY HEART ALONE')
list_titles.append('YOU SAY YOU CARE')
list_titles.append('YOU STEPPED OUT OF A DREAM')
list_titles.append('YOU TOOK ADVANTAGE OF ME')
list_titles.append('ZING WENT THE STRINGS')

list_cadence = []
list_cadence.append('I-#Idim-IIm7-#IIdim-IIIm7')
list_cadence.append('I-#Idim-IIm7-V7')
list_cadence.append('I-I+-IV-#IVdim')
list_cadence.append('I-I7-IV-#IVdim')
list_cadence.append('I-I7-IV-IVm')
list_cadence.append('I-IIm7-IIIm7-IIm7')
list_cadence.append('I-IIm7-IIIm7-bIIIdim')
list_cadence.append('I-III7-IImin')
list_cadence.append('I-III7-IV-II7-V7')
list_cadence.append('I-III7-IV')
list_cadence.append('I-III7-VI7-II7-V7')
list_cadence.append('I-III7-VI7-II7-IIm')
list_cadence.append('I-III7-VI7-II7-IVm')
list_cadence.append('I-III7-VIm-II7')
list_cadence.append('I-IIIm7b5-VI7')
list_cadence.append('I-IV7')
list_cadence.append('I-IVm')
list_cadence.append('I-VI7-II7-V7')
list_cadence.append('I-VI7-IIm7-V7')
list_cadence.append('I-VI7-IV-IVm')
list_cadence.append('I-VI7-VIIm7b5-III7')
list_cadence.append('I-VIm7-IIm7-V7')
list_cadence.append('I-VII7-I')
list_cadence.append('I-VII7-III7-VI7-II7-V7')
list_cadence.append('I-bVII7-VI7')
list_cadence.append('I-bVII7-VI7-II7-V7')
list_cadence.append('I-IV')
list_cadence.append('I-Im7')
list_cadence.append('I-Im')
list_cadence.append('I-II7b5')
list_cadence.append('I-VIm7-IIIm7')
list_cadence.append('Im')
list_cadence.append('I7-IV')
list_cadence.append('I7-IV-III7-VIm-II7')
list_cadence.append('I7-IV-VI7-IIm')
list_cadence.append('I7-IV7-bVII7-bIII7-V7')
list_cadence.append('I7-IVm')
list_cadence.append('I7-VII7-bVII7-VI7')
list_cadence.append('I7+')
list_cadence.append('II')
list_cadence.append('IIm')
list_cadence.append('IIm-VIm')
list_cadence.append('IIm7-V7-downinwholesteps')
list_cadence.append('IIm7-Vm7')
list_cadence.append('IIm7b5-V7')
list_cadence.append('II7')
list_cadence.append('II7-V7')
list_cadence.append('II7-bII7-I')
list_cadence.append('III')
list_cadence.append('IIIm')
list_cadence.append('IIIm7-VI7-II7-IIm7-V7')
list_cadence.append('IIIm7-VI7-IIm7-V7')
list_cadence.append('IIIm7-bIII7-IIm7-bII7-I')
list_cadence.append('IIIm7-bIIIm7-IIm7-V7')
list_cadence.append('IIIm7b5-VI7')
list_cadence.append('IIIm7b5-VI7-IIm7b5-V7')
list_cadence.append('IIIm7b5-VI7-IIm-IIm7-V7')
list_cadence.append('IIIm7b5-VI7-IV-IVm')
list_cadence.append('III7-IV-IVm')
list_cadence.append('III7-VI7-II7-V7')
list_cadence.append('IV')
list_cadence.append('IV-#IVdim-I')
list_cadence.append('IV-IVm')
list_cadence.append('IV-bVI')
list_cadence.append('IVm')
list_cadence.append('IVm6')
list_cadence.append('IV7')
list_cadence.append('IV7-III7-VI7-II7')
list_cadence.append('V')
list_cadence.append('V-VI')
list_cadence.append('Vm')
list_cadence.append('Vm7')
list_cadence.append('V7+')
list_cadence.append('V7sus')
list_cadence.append('VI')
list_cadence.append('VI-V')
list_cadence.append('VIm')
list_cadence.append('VIm-IIm')
list_cadence.append('VIm-II7')
list_cadence.append('VIm-III')
list_cadence.append('VIm-IIIm')
list_cadence.append('VI7-IIm')
list_cadence.append('VI7-II7-V7-I')
list_cadence.append('VI7-IV-IVm')
list_cadence.append('VI7-IV')
list_cadence.append('VII')
list_cadence.append('VII-I')
list_cadence.append('VIIm')
list_cadence.append('VIIm7b5-III7-VIm7-II7I')
list_cadence.append('VII7')
list_cadence.append('VII7-III7-VI7-II7-V7')
list_cadence.append('bII')
list_cadence.append('bIIm')
list_cadence.append('bII7')
list_cadence.append('bII7-bVI7-V7')
list_cadence.append('bIII')
list_cadence.append('bIII-bVI-bII')
list_cadence.append('bIIIm')
list_cadence.append('bIII7')
list_cadence.append('bIIIdim')
list_cadence.append('bV')
list_cadence.append('bVI')
list_cadence.append('bVI-bV')
list_cadence.append('bVI7')
list_cadence.append('bVI7-V7')
list_cadence.append('bVII')
list_cadence.append('bVIIm')
list_cadence.append('bVII7-VI7')
list_cadence.append('bVII7-VI7-II7')
list_cadence.append('bVII7-VI7-II7-V7')
list_cadence.append('bVII7-VI7-IIm')
list_cadence.append('bVII7-VI7-bVI7-V7')
list_cadence.append('start_IV')
list_cadence.append('start_IV-IVm')
list_cadence.append('start_II7')
list_cadence.append('start_bVI7-V7')
list_cadence.append('start_VIm-VIm/maj7-VIm7-VIm6')
list_cadence.append('start_VIm7')
list_cadence.append('IIm7-V7_down_in_half_steps')
list_cadence.append('A_section_IIm7-V7')


list_bridge = []
list_bridge.append('I')
list_bridge.append('Im')
list_bridge.append('I7-VII7-bVII7-VI7')
list_bridge.append('II')
list_bridge.append('IIm')
list_bridge.append('III')
list_bridge.append('IIIm')
list_bridge.append('III7-VI7-II7-V7')
list_bridge.append('IV')
list_bridge.append('IV-I')
list_bridge.append('IV-IIm')
list_bridge.append('IV-III7-VI7-II7-V7')
list_bridge.append('IV-III')
list_bridge.append('IV-IVm')
list_bridge.append('IV-V_or_IV-II7-V7')
list_bridge.append('IV-bIII')
list_bridge.append('IV-bVI')
list_bridge.append('IV-#IVdim-I')
list_bridge.append('IVm')
list_bridge.append('IV7')
list_bridge.append('V')
list_bridge.append('V-VI')
list_bridge.append('Vm')
list_bridge.append('VI7-II7-V7')
list_bridge.append('VI')
list_bridge.append('VIm')
list_bridge.append('VIm-IIm')
list_bridge.append('VII')
list_bridge.append('VIIm')
list_bridge.append('bII')
list_bridge.append('bII7')
list_bridge.append('bIII')
list_bridge.append('bIII7')
list_bridge.append('bV')
list_bridge.append('bVI')
list_bridge.append('bVI-bV')
list_bridge.append('bVI7')
list_bridge.append('bVII')
list_bridge.append('bVII-bV')
list_bridge.append('5th_cycle')
list_bridge.append('V7_down_chroma')
list_bridge.append('IIm7-V7_down_whole_steps')
list_bridge.append('IIm7b5-V7_down_whole_steps')

artist_list = []
artist_list.append('Ahmad Jamal')
artist_list.append('Al Foster')
artist_list.append('Al Haig')
artist_list.append('Alphonse Mouzon')
artist_list.append('Anita O\'Day')
artist_list.append('Archie Shepp')
artist_list.append('Art Blakey')
artist_list.append('Artie Shaw')
artist_list.append('Art Pepper')
artist_list.append('Art Tatum')
artist_list.append('Attila Zoller')
artist_list.append('Azar Lwarence')
artist_list.append('Barney Kessel')
artist_list.append('Benny Golson')
artist_list.append('Benny Goodman')
artist_list.append('Ben Webster')
artist_list.append('Betty Carter')
artist_list.append('Bill Evans')
artist_list.append('Bill Harris')
artist_list.append('Billie Holiday')
artist_list.append('Bill Watrous')
artist_list.append('Billy Cobham')
artist_list.append('Billy Eckstine')
artist_list.append('Billy Hart')
artist_list.append('Billy Higgins')
artist_list.append('Billy Pierce')
artist_list.append('Blue Mitchell')
artist_list.append('Bob Berg')
artist_list.append('Bobby Hutcherson')
artist_list.append('Bobby Moses')
artist_list.append('Bob Cranshaw')
artist_list.append('Buddy DeFranco')
artist_list.append('Buddy Rich')
artist_list.append('Bud Powell')
artist_list.append('Bud Shank')
artist_list.append('Bunky Green')
artist_list.append('Buster Williams')
artist_list.append('Cal Tjader')
artist_list.append('Cannonball Adderley')
artist_list.append('Carl Fontana')
artist_list.append('Carmen McRae')
artist_list.append('Carol Kaye')
artist_list.append('Cecil McBee')
artist_list.append('Charles Lloyd')
artist_list.append('Charles Mingus')
artist_list.append('Charlie Christian')
artist_list.append('Charlie Mariano')
artist_list.append('Charlie Parker')
artist_list.append('Chet Baker')
artist_list.append('Chich Corea')
artist_list.append('Chris Connors')
artist_list.append('Chuck Rainey')
artist_list.append('Clark Terry')
artist_list.append('Clifford Brown')
artist_list.append('Clifford Johnson')
artist_list.append('Coleman Hawkins')
artist_list.append('Connie Kay')
artist_list.append('Curtis Fuller')
artist_list.append('Dakota Staton')
artist_list.append('Danny Richmond')
artist_list.append('Dave Friedman')
artist_list.append('Dave Liebman')
artist_list.append('Dave Pike')
artist_list.append('Denny Zeitlin')
artist_list.append('Dewey Redman')
artist_list.append('Dexter Gordon')
artist_list.append('Dizzy Gillespie')
artist_list.append('Django Reinhardt')
artist_list.append('Don Cherry')
artist_list.append('Doug Raney')
artist_list.append('Ed Blackwell')
artist_list.append('Eddie Gomez')
artist_list.append('Ella Fitzgerald')
artist_list.append('Elvin Jones')
artist_list.append('Eric Dolphy')
artist_list.append('Eric Dolphy')
artist_list.append('Eric Kloss')
artist_list.append('Fats Navarro')
artist_list.append('Frank Rosolino')
artist_list.append('Frank Sinatra')
artist_list.append('Frank Wess')
artist_list.append('Freddie Hubbard')
artist_list.append('Garnett Brown')
artist_list.append('Gary Burton')
artist_list.append('Gene Ammons')
artist_list.append('George Benson')
artist_list.append('George Cables')
artist_list.append('George Coleman')
artist_list.append('George Duke')
artist_list.append('George Duvivier')
artist_list.append('George Mraz')
artist_list.append('Grachan Moncur')
artist_list.append('Grady Tate')
artist_list.append('Grant Green')
artist_list.append('Hampton Hawes')
artist_list.append('Hank Mobley')
artist_list.append('Harold Land')
artist_list.append('Herb Ellis')
artist_list.append('Herb Geller')
artist_list.append('Herbie Hancocl')
artist_list.append('Herbie Mann')
artist_list.append('Horace Silver')
artist_list.append('Hubert Laws')
artist_list.append('Israel Crosby')
artist_list.append('Jack DeJohnette')
artist_list.append('Jackie Cain')
artist_list.append('Jackie McLean')
artist_list.append('Jack McDuff')
artist_list.append('Jack Teagarden')
artist_list.append('Jaco Pastorius')
artist_list.append('James Moody')
artist_list.append('Jean-Luc Ponty')
artist_list.append('Jeremy Steig')
artist_list.append('Jerry Goodman')
artist_list.append('Jerry Hahn')
artist_list.append('Jim Hall')
artist_list.append('Jimmy Blanton')
artist_list.append('Jimmy Cleveland')
artist_list.append('Jimmy Garrison')
artist_list.append('Jimmy Giuffre')
artist_list.append('Jimmy McGriff')
artist_list.append('Jimmy Raney')
artist_list.append('Jimmy Smith')
artist_list.append('J.J. Johnson')
artist_list.append('Joe Chambers')
artist_list.append('Joe Farrell')
artist_list.append('Joe Henderson')
artist_list.append('Joe Pass')
artist_list.append('Joe Venuti')
artist_list.append('Joe Williams')
artist_list.append('Joe Zawinul')
artist_list.append('John Blake')
artist_list.append('John Coltrane')
artist_list.append('John Klemmer')
artist_list.append('John Lewis')
artist_list.append('John McLaughlin')
artist_list.append('John McNeil')
artist_list.append('Johnny Coles')
artist_list.append('John Patton')
artist_list.append('Jon Lucien')
artist_list.append('June Christ')
artist_list.append('Kai Winding')
artist_list.append('Keith Jarrett')
artist_list.append('Kenny Barron')
artist_list.append('Kenny Burrell')
artist_list.append('Kenny Clarke')
artist_list.append('Kenny Dorham')
artist_list.append('Larry Coryell')
artist_list.append('Larry Young')
artist_list.append('Lee Konitz')
artist_list.append('Lee Morgan')
artist_list.append('Lennie Niehaus')
artist_list.append('Lennie Tristano')
artist_list.append('Lenny White')
artist_list.append('Leon Thomas')
artist_list.append('Lester Young')
artist_list.append('Lionel Hampton')
artist_list.append('Lou Donaldson')
artist_list.append('Louis Bellson')
artist_list.append('Lou Rawls')
artist_list.append('Lynn Blessing')
artist_list.append('Mary Lou Williams')
artist_list.append('Max Roach')
artist_list.append('McCoy Tyner')
artist_list.append('Mel Torme')
artist_list.append('Michael Brecker')
artist_list.append('Michael White')
artist_list.append('Mick Goodrick')
artist_list.append('Micky Roker')
artist_list.append('Miles Davis')
artist_list.append('Milt Bernhardt')
artist_list.append('Milt Hinton')
artist_list.append('Milt Jackson')
artist_list.append('Miroslav Vitous')
artist_list.append('Monk Montgomery')
artist_list.append('Mose Allison')
artist_list.append('Niels-Henning Ørsted Pedersen')
artist_list.append('Ornette Coleman')
artist_list.append('Oscar Peterson')
artist_list.append('Oscar Pettiford')
artist_list.append('Pat Martino')
artist_list.append('Paul Bley')
artist_list.append('Paul Chambers')
artist_list.append('Paul Desmond')
artist_list.append('Paul Motian')
artist_list.append('Pee Wee Russell')
artist_list.append('Peggy Lee')
artist_list.append('Percy Heath')
artist_list.append('Pharoah Sanders')
artist_list.append('Philly Joe Jones')
artist_list.append('Phil Wilson')
artist_list.append('Phil Woods')
artist_list.append('Phineas Newborn Jr.')
artist_list.append('Randy Sabien')
artist_list.append('Ray Brown')
artist_list.append('Ray Charles')
artist_list.append('Ray Nance')
artist_list.append('Red Garland')
artist_list.append('Red Mitchell')
artist_list.append('Red Norvo')
artist_list.append('Richard Davis')
artist_list.append('Richard Holmes')
artist_list.append('Richie Cole')
artist_list.append('Roland Hanna')
artist_list.append('Roland Kirk')
artist_list.append('Ron Carter')
artist_list.append('Roscoe Mitchell')
artist_list.append('Roswell Rudd')
artist_list.append('Roy Ayers')
artist_list.append('Roy Eldridge')
artist_list.append('Roy Haynes')
artist_list.append('Roy Kral')
artist_list.append('Rufus Reid')
artist_list.append('Russell Procope')
artist_list.append('Sam Jones')
artist_list.append('Sarah Vaughan')
artist_list.append('Scott LaFaro')
artist_list.append('Shelly Manne')
artist_list.append('Slam Stewart')
artist_list.append('Sonny Rollins')
artist_list.append('Sonny Stitt')
artist_list.append('Stan Getz')
artist_list.append('Stan Levy')
artist_list.append('Stanley Clarke')
artist_list.append('Stéphane Grappelli')
artist_list.append('Steve Grossman')
artist_list.append('Steve Swallow')
artist_list.append('Stuff Smith')
artist_list.append('Tal Farlow')
artist_list.append('Terry Gibbs')
artist_list.append('Terumaso Hino')
artist_list.append('Thelonious Monk')
artist_list.append('Tom Harrell')
artist_list.append('Tommy Flanagan')
artist_list.append('Tony Scott')
artist_list.append('Tony Williams')
artist_list.append('Virgil Jones')
artist_list.append('Warn Marsh')
artist_list.append('Wayne Shorter')
artist_list.append('Wes Montgomery')
artist_list.append('Woody Herman')
artist_list.append('Woody Shaw')
artist_list.append('Wynton Kelly')
artist_list.append('Wynton Marsalis')
artist_list.append('Yusef Lateef')
artist_list.append('Zoot Sims')

list_transcript = []
list_transcript.append('ArtPepper_Anthropology')
list_transcript.append('ArtPepper_BluesForBlanche')
list_transcript.append('ArtPepper_Desafinado')
list_transcript.append('ArtPepper_InAMellowTone')
list_transcript.append('ArtPepper_Stardust-1')
list_transcript.append('ArtPepper_Stardust-2')
list_transcript.append('BennyCarter_IGotItBad')
list_transcript.append('BennyCarter_It\'sAWonderfulWorld-1')
list_transcript.append('BennyCarter_It\'sAWonderfulWorld-2')
list_transcript.append('BennyCarter_JustFriends')
list_transcript.append('BennyCarter_LongAgoAndFarAway-1')
list_transcript.append('BennyCarter_LongAgoAndFarAway-2')
list_transcript.append('BennyCarter_SweetLorraine')
list_transcript.append('BennyGoodman_Avalon')
list_transcript.append('BennyGoodman_HandfulOfKeys')
list_transcript.append('BennyGoodman_Nobody\'sSweetheart')
list_transcript.append('BennyGoodman_Runnin\'Wild')
list_transcript.append('BennyGoodman_TigerRag-1')
list_transcript.append('BennyGoodman_TigerRag-2')
list_transcript.append('BennyGoodman_Whispering')
list_transcript.append('BenWebster_ByeByeBlackbird')
list_transcript.append('BenWebster_DidYouCallHerToday')
list_transcript.append('BenWebster_MyIdeal')
list_transcript.append('BenWebster_NightAndDay')
list_transcript.append('BenWebster_WhereOrWhen')
list_transcript.append('BixBeiderbecke_I\'mComingVirginia')
list_transcript.append('BixBeiderbecke_Margie')
list_transcript.append('BixBeiderbecke_RiverboatShuffle')
list_transcript.append('BixBeiderbecke_RoyalGardenBlues')
list_transcript.append('BixBeiderbecke_SinginTheBlues')
list_transcript.append('BobBerg_Angles')
list_transcript.append('BobBerg_BluesForBela')
list_transcript.append('BobBerg_IDidn\'tKnowWhatTimeItWas')
list_transcript.append('BobBerg_NatureOfTheBeast')
list_transcript.append('BobBerg_NoMoe')
list_transcript.append('BobBerg_SecondSight')
list_transcript.append('BobBerg_YouAndTheNightAndTheMusic')
list_transcript.append('BranfordMarsalis_GutbucketSteepy')
list_transcript.append('BranfordMarsalis_HousedFromEdward-1')
list_transcript.append('BranfordMarsalis_HousedFromEdward-2')
list_transcript.append('BranfordMarsalis_TheNearnessOfYou')
list_transcript.append('BranfordMarsalis_ThreeLittleWords')
list_transcript.append('BranfordMarsalis_U.M.M.G.')
list_transcript.append('BuckClayton_AfterTheatreJump')
list_transcript.append('BuckClayton_DestinationK.C.')
list_transcript.append('BuckClayton_Dickie\'sDream')
list_transcript.append('CannonballAdderley_HighFly')
list_transcript.append('CannonballAdderley_SoWhat')
list_transcript.append('CannonballAdderley_StarEyes')
list_transcript.append('CannonballAdderley_ThisHere')
list_transcript.append('CannonballAdderley_WorkSong')
list_transcript.append('CharlieParker_Billie\'sBounce')
list_transcript.append('CharlieParker_BluesForAlice')
list_transcript.append('CharlieParker_Don\'tBlameMe')
list_transcript.append('CharlieParker_DonnaLee')
list_transcript.append('CharlieParker_EmbraceableYou')
list_transcript.append('CharlieParker_HowDeepIsTheOcean')
list_transcript.append('CharlieParker_K.C.Blues')
list_transcript.append('CharlieParker_Ko-Ko')
list_transcript.append('CharlieParker_MyLittleSuedeShoes')
list_transcript.append('CharlieParker_Ornithology')
list_transcript.append('CharlieParker_OutOfNowhere')
list_transcript.append('CharlieParker_ScrappleFromTheApple')
list_transcript.append('CharlieParker_Segment')
list_transcript.append('CharlieParker_StarEyes')
list_transcript.append('CharlieParker_Steeplechase')
list_transcript.append('CharlieParker_ThrivingOnARiff')
list_transcript.append('CharlieParker_YardbirdSuite')
list_transcript.append('CharlieShavers_LimehouseBlues')
list_transcript.append('ChetBaker_IFallInLoveTooEasily')
list_transcript.append('ChetBaker_JustFriends')
list_transcript.append('ChetBaker_Let\'sGetLost')
list_transcript.append('ChetBaker_LongAgoAndFarAway')
list_transcript.append('ChetBaker_ThereWillNeverBeAnotherYou-1')
list_transcript.append('ChetBaker_ThereWillNeverBeAnotherYou-2')
list_transcript.append('ChetBaker_Two\'sBlues')
list_transcript.append('ChetBaker_You\'dBeSoNiceToComeHomeTo')
list_transcript.append('ChrisPotter_Anthropology')
list_transcript.append('ChrisPotter_Arjuna')
list_transcript.append('ChrisPotter_InASentimentalMood')
list_transcript.append('ChrisPotter_Item1,D.I.T.')
list_transcript.append('ChrisPotter_PopTune#1')
list_transcript.append('ChrisPotter_Rumples')
list_transcript.append('ChrisPotter_Togo')
list_transcript.append('ChuBerry_BodyAndSoul-1')
list_transcript.append('ChuBerry_BodyAndSoul-2')
list_transcript.append('CliffordBrown_ANightInTunisia')
list_transcript.append('CliffordBrown_Daahoud')
list_transcript.append('CliffordBrown_George\'sDilemma')
list_transcript.append('CliffordBrown_I\'llRememberApril_AlternateTake2')
list_transcript.append('CliffordBrown_I\'llRememberApril')
list_transcript.append('CliffordBrown_Jordu')
list_transcript.append('CliffordBrown_JoySpring')
list_transcript.append('CliffordBrown_Sandu')
list_transcript.append('CliffordBrown_Stompin\'AtTheSavoy')
list_transcript.append('ColemanHawkins_BodyAndSoul')
list_transcript.append('ColemanHawkins_It\'sOnlyAPapermoon')
list_transcript.append('ColemanHawkins_MyBlueHeaven')
list_transcript.append('ColemanHawkins_Perdido')
list_transcript.append('ColemanHawkins_SophisticatedLady')
list_transcript.append('ColemanHawkins_Stompin\'AtTheSavoy')
list_transcript.append('CurtisFuller_BlueTrain')
list_transcript.append('CurtisFuller_DownUnder')
list_transcript.append('DavidLiebman_BeginTheBeguine')
list_transcript.append('DavidLiebman_Day&Nite')
list_transcript.append('DavidLiebman_I\'veGotYouUnderMySkin')
list_transcript.append('DavidLiebman_Milestones')
list_transcript.append('DavidLiebman_Nica\'sDream')
list_transcript.append('DavidLiebman_NoGreaterLove')
list_transcript.append('DavidLiebman_Pablo\'sStory')
list_transcript.append('DavidLiebman_Pendulum')
list_transcript.append('DavidLiebman_SecretLove')
list_transcript.append('DavidLiebman_SoftlyAsInAMorningSunrise')
list_transcript.append('DavidLiebman_ThereWillNeverBeAnotherYou')
list_transcript.append('DavidMurray_AskMeNow')
list_transcript.append('DavidMurray_BluesForTwo-1')
list_transcript.append('DavidMurray_BluesForTwo-2')
list_transcript.append('DavidMurray_BodyAndSoul-1')
list_transcript.append('DavidMurray_BodyAndSoul-2')
list_transcript.append('DavidMurray_ChelseaBridge')
list_transcript.append('DexterGordon_Cheesecake')
list_transcript.append('DexterGordon_Dextivity')
list_transcript.append('DexterGordon_Montmartre')
list_transcript.append('DexterGordon_SocietyRed')
list_transcript.append('DexterGordon_StanleyTheSteamer')
list_transcript.append('DexterGordon_TheRainbowPeople')
list_transcript.append('DickieWells_AfterTheatreJump')
list_transcript.append('DickieWells_DestinationK.C.')
list_transcript.append('DickieWells_Dickie\'sDream')
list_transcript.append('DickieWells_IGotRhythm')
list_transcript.append('DickieWells_Jo-Jo')
list_transcript.append('DickieWells_SixCatsAndAPrince')
list_transcript.append('DizzyGillespie_Anthropology')
list_transcript.append('DizzyGillespie_Be-Bop')
list_transcript.append('DizzyGillespie_Blue\'nBoogie')
list_transcript.append('DizzyGillespie_CognacBlues')
list_transcript.append('DizzyGillespie_Groovin\'High')
list_transcript.append('DizzyGillespie_HotHouse')
list_transcript.append('DonByas_Be-Bop')
list_transcript.append('DonByas_BodyAndSoul')
list_transcript.append('DonByas_CognacBlues')
list_transcript.append('DonByas_HarvardBlues-1')
list_transcript.append('DonByas_HarvardBlues-2')
list_transcript.append('DonByas_Infidele(Cry)')
list_transcript.append('DonByas_OutOfNowhere')
list_transcript.append('DonByas_UnAmourPleurait')
list_transcript.append('DonEllis_ILoveYou')
list_transcript.append('DonEllis_JohnnyComeLately')
list_transcript.append('DonEllis_OutOfNowhere')
list_transcript.append('DonEllis_SweetAndLovely')
list_transcript.append('DonEllis_YouSteppedOutOfADream-1')
list_transcript.append('DonEllis_YouSteppedOutOfADream-2')
list_transcript.append('EricDolphy_245')
list_transcript.append('EricDolphy_Aisha')
list_transcript.append('EricDolphy_DahomeyDance')
list_transcript.append('EricDolphy_Les')
list_transcript.append('EricDolphy_OnGreenDolphinStreet')
list_transcript.append('EricDolphy_Serene')
list_transcript.append('FatsNavarro_Anthropology_No1')
list_transcript.append('FatsNavarro_DoubleTalk')
list_transcript.append('FatsNavarro_GoodBait_AlternateTake')
list_transcript.append('FatsNavarro_GoodBait')
list_transcript.append('FatsNavarro_OurDelight')
list_transcript.append('FatsNavarro_TheSkunk')
list_transcript.append('FreddieHubbard_245')
list_transcript.append('FreddieHubbard_DolphinDance')
list_transcript.append('FreddieHubbard_DownUnder')
list_transcript.append('FreddieHubbard_MaidenVoyage')
list_transcript.append('FreddieHubbard_SocietyRed')
list_transcript.append('FreddieHubbard_SpeakNoEvil')
list_transcript.append('GeorgeColeman_MaidenVoyage')
list_transcript.append('GerryMulligan_Bunny')
list_transcript.append('GerryMulligan_LineForLyons')
list_transcript.append('GerryMulligan_ScrappleFromTheApple')
list_transcript.append('GerryMulligan_TheRedDoor')
list_transcript.append('GerryMulligan_ThisCan\'tBeLove')
list_transcript.append('GerryMulligan_WalkingShoes')
list_transcript.append('HankMobley_Doodlin\'')
list_transcript.append('HankMobley_LadyBird')
list_transcript.append('HankMobley_Remember')
list_transcript.append('HankMobley_SoulStation')
list_transcript.append('HarryEdison_DidYouCallHerToday')
list_transcript.append('HenryAllen_BabyWon\'tYouPleaseComeHome')
list_transcript.append('HerbieHancock_Agitation')
list_transcript.append('HerbieHancock_Dolores')
list_transcript.append('HerbieHancock_GingerbreadBoy')
list_transcript.append('HerbieHancock_HandJive')
list_transcript.append('HerbieHancock_Orbits')
list_transcript.append('JCHigginbotham_BabyWon\'tYouPleaseComeHome')
list_transcript.append('JJJohnson_BlueMode')
list_transcript.append('JJJohnson_BluesInTheCloset')
list_transcript.append('JJJohnson_CrazyRhythm')
list_transcript.append('JJJohnson_Elora')
list_transcript.append('JJJohnson_MyFunnyValentine')
list_transcript.append('JJJohnson_Teapot')
list_transcript.append('JJJohnson_Walkin\'')
list_transcript.append('JJJohnson_Yesterdays')
list_transcript.append('JoeHenderson_In\'NOut-1')
list_transcript.append('JoeHenderson_In\'NOut-2')
list_transcript.append('JoeHenderson_JohnnyComeLately')
list_transcript.append('JoeHenderson_Punjab')
list_transcript.append('JoeHenderson_Serenity')
list_transcript.append('JoeHenderson_TheSidewinder')
list_transcript.append('JoeHenderson_TotemPole')
list_transcript.append('JoeHenderson_U.M.M.G.')
list_transcript.append('JoeLovano_BodyAndSoul-1')
list_transcript.append('JoeLovano_BodyAndSoul-2')
list_transcript.append('JoeLovano_CentralParkWest')
list_transcript.append('JoeLovano_ConAlma')
list_transcript.append('JoeLovano_ICan\'tGetStarted')
list_transcript.append('JoeLovano_LittleWillieLeapsIn')
list_transcript.append('JoeLovano_Lonnie\'sLament-1')
list_transcript.append('JoeLovano_Work')
list_transcript.append('JohnAbercrombie_Ralph\'sPianoWaltz')
list_transcript.append('JohnColtrane_26-2')
list_transcript.append('JohnColtrane_Bessie\'sBlues')
list_transcript.append('JohnColtrane_BluesByFive')
list_transcript.append('JohnColtrane_BlueTrain')
list_transcript.append('JohnColtrane_BodyAndSoul_AlternateTake')
list_transcript.append('JohnColtrane_BodyAndSoul')
list_transcript.append('JohnColtrane_Countdown')
list_transcript.append('JohnColtrane_GiantSteps-1')
list_transcript.append('JohnColtrane_GiantSteps-2')
list_transcript.append('JohnColtrane_Impressions_1961')
list_transcript.append('JohnColtrane_Impressions_1963')
list_transcript.append('JohnColtrane_Mr.P.C.')
list_transcript.append('JohnColtrane_MyFavoriteThings-1')
list_transcript.append('JohnColtrane_MyFavoriteThings-2')
list_transcript.append('JohnColtrane_NatureBoy')
list_transcript.append('JohnColtrane_Nutty')
list_transcript.append('JohnColtrane_Oleo')
list_transcript.append('JohnColtrane_Soultrane')
list_transcript.append('JohnColtrane_SoWhat')
list_transcript.append('JohnColtrane_Trane\'sBlues')
list_transcript.append('JohnnyDodds_GotNoBlues')
list_transcript.append('JohnnyDodds_HeebieJeebies')
list_transcript.append('JohnnyDodds_HotterThanThat')
list_transcript.append('JohnnyDodds_MuskratRamble')
list_transcript.append('JohnnyDodds_MyHeart')
list_transcript.append('JohnnyDodds_OnceInAWhile')
list_transcript.append('JohnnyHodges_Bunny')
list_transcript.append('JohnnyHodges_EarlyMorningRock')
list_transcript.append('JoshuaRedman_BluesOnSunday')
list_transcript.append('JoshuaRedman_HomeFries')
list_transcript.append('JoshuaRedman_IGotYou')
list_transcript.append('JoshuaRedman_SweetSorrow')
list_transcript.append('JoshuaRedman_TearsInHeaven')
list_transcript.append('KaiWinding_Tiny\'sBlues')
list_transcript.append('KennyDorham_BluesInBe-Bop')
list_transcript.append('KennyDorham_Doodlin\'')
list_transcript.append('KennyDorham_In\'NOut')
list_transcript.append('KennyDorham_LadyBird')
list_transcript.append('KennyDorham_PrinceAlbert')
list_transcript.append('KennyDorham_Punjab')
list_transcript.append('KennyDorham_Serenity')
list_transcript.append('KennyGarrett_BrotherHubbard-1')
list_transcript.append('KennyGarrett_BrotherHubbard-2')
list_transcript.append('KennyWheeler_DoubleVision')
list_transcript.append('KennyWheeler_PassItOn')
list_transcript.append('KennyWheeler_SlippedAgain')
list_transcript.append('KidOry_GotNoBlues')
list_transcript.append('KidOry_GutBucketBlues')
list_transcript.append('KidOry_MuskratRamble')
list_transcript.append('KidOry_SavoyBlues')
list_transcript.append('KidOry_Who\'sIt')
list_transcript.append('LeeKonitz_AllTheThingsYouAre')
list_transcript.append('LeeKonitz_BopGoesToLeesel')
list_transcript.append('LeeKonitz_Crosscurrent')
list_transcript.append('LeeKonitz_I\'llRememberApril')
list_transcript.append('LeeKonitz_Marshmallow')
list_transcript.append('LeeKonitz_MeanToMe')
list_transcript.append('LeeKonitz_Tautology')
list_transcript.append('LeeKonitz_Wow')
list_transcript.append('LeeMorgan_BlueTrain')
list_transcript.append('LeeMorgan_JustOneOfThoseThings')
list_transcript.append('LeeMorgan_TheSidewinder')
list_transcript.append('LeeMorgan_TotemPole')
list_transcript.append('LesterYoung_AfterTheatreJump')
list_transcript.append('LesterYoung_BodyAndSoul')
list_transcript.append('LesterYoung_D.B.Blues')
list_transcript.append('LesterYoung_DestinationK.C.')
list_transcript.append('LesterYoung_Dickie\'sDream')
list_transcript.append('LesterYoung_LesterLeapsIn')
list_transcript.append('LesterYoung_SixCatsAndAPrince')
list_transcript.append('LionelHampton_Avalon')
list_transcript.append('LionelHampton_Dinah')
list_transcript.append('LionelHampton_HighSociety')
list_transcript.append('LionelHampton_MemoriesOfYou')
list_transcript.append('LionelHampton_Runnin\'Wild')
list_transcript.append('LionelHampton_Whispering')
list_transcript.append('LouisArmstrong_BasinStreetBlues')
list_transcript.append('LouisArmstrong_BigButterAndEggMan')
list_transcript.append('LouisArmstrong_CornetChopSuey')
list_transcript.append('LouisArmstrong_GotNoBlues')
list_transcript.append('LouisArmstrong_GutBucketBlues')
list_transcript.append('LouisArmstrong_MuskratRamble')
list_transcript.append('LouisArmstrong_OnceInAWhile')
list_transcript.append('LouisArmstrong_SavoyBlues')
list_transcript.append('MichaelBrecker_CabinFever')
list_transcript.append('MichaelBrecker_Confirmation')
list_transcript.append('MichaelBrecker_DeltaCityBlues')
list_transcript.append('MichaelBrecker_IMeanYou')
list_transcript.append('MichaelBrecker_MidnightVoyage')
list_transcript.append('MichaelBrecker_NakedSoul')
list_transcript.append('MichaelBrecker_NeverAlone')
list_transcript.append('MichaelBrecker_NothingPersonal')
list_transcript.append('MichaelBrecker_Peep')
list_transcript.append('MichaelBrecker_SongForBilbao')
list_transcript.append('MilesDavis_Agitation')
list_transcript.append('MilesDavis_Airegin')
list_transcript.append('MilesDavis_BitchesBrew-1')
list_transcript.append('MilesDavis_BitchesBrew-2')
list_transcript.append('MilesDavis_BluesByFive')
list_transcript.append('MilesDavis_Dolores')
list_transcript.append('MilesDavis_E.S.P.')
list_transcript.append('MilesDavis_Eighty-One')
list_transcript.append('MilesDavis_K.C.Blues')
list_transcript.append('MilesDavis_MilesRunsTheVoodooDown-1')
list_transcript.append('MilesDavis_MilesRunsTheVoodooDown-2')
list_transcript.append('MilesDavis_Oleo-1')
list_transcript.append('MilesDavis_Oleo-2')
list_transcript.append('MilesDavis_Orbits')
list_transcript.append('MilesDavis_SoWhat')
list_transcript.append('MilesDavis_Trane\'sBlues')
list_transcript.append('MilesDavis_TuneUp')
list_transcript.append('MilesDavis_VierdBlues')
list_transcript.append('MilesDavis_Walkin\'')
list_transcript.append('MiltJackson_AllTheThingsYouAre')
list_transcript.append('MiltJackson_Bag\'sGroove')
list_transcript.append('MiltJackson_BemshaSwing')
list_transcript.append('MiltJackson_Don\'tGetAroundMuchAnymore')
list_transcript.append('MiltJackson_SoftlyAsInAMorningSunrise')
list_transcript.append('MiltJackson_What\'sNew')
list_transcript.append('NatAdderley_BohemiaAfterDark')
list_transcript.append('NatAdderley_WorkSong')
list_transcript.append('OrnetteColeman_BirdFood')
list_transcript.append('OrnetteColeman_Chronology')
list_transcript.append('OrnetteColeman_Congeniality')
list_transcript.append('OrnetteColeman_Peace')
list_transcript.append('OrnetteColeman_Ramblin\'')
list_transcript.append('PatMartino_AlongCameBetty')
list_transcript.append('PatMetheny_AllTheThingsYouAre')
list_transcript.append('PatMetheny_CabinFever')
list_transcript.append('PatMetheny_MidnightVoyage')
list_transcript.append('PatMetheny_NothingPersonal')
list_transcript.append('PaulDesmond_Alianca-1')
list_transcript.append('PaulDesmond_Alianca-2')
list_transcript.append('PaulDesmond_AloneTogether')
list_transcript.append('PaulDesmond_BlueRondoALaTurk')
list_transcript.append('PaulDesmond_BossaAntigua')
list_transcript.append('PaulDesmond_SambaCantina-1')
list_transcript.append('PaulDesmond_SambaCantina-2')
list_transcript.append('PaulDesmond_TheGirlFromEast9thStreet')
list_transcript.append('PepperAdams_ANightInTunisia')
list_transcript.append('PepperAdams_EarlyMorningMood')
list_transcript.append('PepperAdams_HowHighTheMoon')
list_transcript.append('PepperAdams_JustOneOfThoseThings')
list_transcript.append('PepperAdams_You\'dBeSoNiceToComeHomeTo')
list_transcript.append('PhilWoods_BeMyLove')
list_transcript.append('PhilWoods_CottonTail')
list_transcript.append('PhilWoods_CrazyRhythm')
list_transcript.append('PhilWoods_HoneysuckleRose')
list_transcript.append('PhilWoods_OnASlowBoatToChina')
list_transcript.append('PhilWoods_Strollin\'WithPam')
list_transcript.append('RayNance_TakeTheATrain')
list_transcript.append('RedGarland_Oleo')
list_transcript.append('RexStewart_Perdido')
list_transcript.append('RoyEldridge_BodyAndSoul')
list_transcript.append('RoyEldridge_KingDavid')
list_transcript.append('RoyEldridge_St.LouisBlues')
list_transcript.append('RoyEldridge_TheGasser-1')
list_transcript.append('RoyEldridge_TheGasser-2')
list_transcript.append('RoyEldridge_Undecided')
list_transcript.append('SidneyBechet_BabyWon\'tYouPleaseComeHome')
list_transcript.append('SidneyBechet_I\'mComingVirginia')
list_transcript.append('SidneyBechet_LimehouseBlues')
list_transcript.append('SidneyBechet_ReallyTheBlues')
list_transcript.append('SidneyBechet_Summertime')
list_transcript.append('SonnyRollins_Airegin')
list_transcript.append('SonnyRollins_BlueSeven-1')
list_transcript.append('SonnyRollins_BlueSeven-2')
list_transcript.append('SonnyRollins_BlueSeven-3')
list_transcript.append('SonnyRollins_I\'llRememberApril_AlternateTake2')
list_transcript.append('SonnyRollins_Playin\'InTheYard-1')
list_transcript.append('SonnyRollins_Playin\'InTheYard-2')
list_transcript.append('SonnyRollins_St.Thomas-1')
list_transcript.append('SonnyRollins_St.Thomas-2')
list_transcript.append('SonnyRollins_TenorMadness')
list_transcript.append('SonnyRollins_TheEverywhereCalypso-1')
list_transcript.append('SonnyRollins_TheEverywhereCalypso-2')
list_transcript.append('SonnyRollins_VierdBlues')
list_transcript.append('SonnyStitt_BlueMode')
list_transcript.append('SonnyStitt_BluesInBe-Bop')
list_transcript.append('SonnyStitt_BodyAndSoul')
list_transcript.append('SonnyStitt_Elora')
list_transcript.append('SonnyStitt_GoodKick')
list_transcript.append('SonnyStitt_Teapot')
list_transcript.append('StanGetz_BluesInTheCloset')
list_transcript.append('StanGetz_BodyAndSoul')
list_transcript.append('StanGetz_CrazyRhythm')
list_transcript.append('StanGetz_I\'mGladThereIsYou')
list_transcript.append('StanGetz_Insensatez')
list_transcript.append('StanGetz_MyFunnyValentine')
list_transcript.append('SteveColeman_Cross-Fade-1')
list_transcript.append('SteveColeman_Cross-Fade-2')
list_transcript.append('SteveColeman_DoubleVision')
list_transcript.append('SteveColeman_PassItOn')
list_transcript.append('SteveColeman_Processional')
list_transcript.append('SteveColeman_Segment')
list_transcript.append('SteveColeman_SlippedAgain')
list_transcript.append('SteveColeman_TakeTheColtrane')
list_transcript.append('SteveColeman_TheOracle-1')
list_transcript.append('SteveColeman_TheOracle-2')
list_transcript.append('SteveLacy_AloneTogether')
list_transcript.append('SteveLacy_AskMeNow')
list_transcript.append('SteveLacy_EasyToLove')
list_transcript.append('SteveLacy_Let\'sCoolOne')
list_transcript.append('SteveLacy_Skippy')
list_transcript.append('SteveLacy_Work')
list_transcript.append('SteveTurre_DatDere')
list_transcript.append('SteveTurre_IfIWereABell')
list_transcript.append('SteveTurre_Steve\'sBlues')
list_transcript.append('VonFreeman_PassItOn')
list_transcript.append('WarneMarsh_Crosscurrent')
list_transcript.append('WarneMarsh_Tautology')
list_transcript.append('WarneMarsh_Wow')
list_transcript.append('WayneShorter_Adam\'sApple')
list_transcript.append('WayneShorter_Dolores')
list_transcript.append('WayneShorter_DownUnder')
list_transcript.append('WayneShorter_E.S.P.')
list_transcript.append('WayneShorter_Eighty-One')
list_transcript.append('WayneShorter_Footprints')
list_transcript.append('WayneShorter_InfantEyes')
list_transcript.append('WayneShorter_Juju')
list_transcript.append('WayneShorter_Orbits')
list_transcript.append('WayneShorter_SpeakNoEvil')
list_transcript.append('WoodyShaw_DatDere')
list_transcript.append('WoodyShaw_IfIWereABell')
list_transcript.append('WoodyShaw_Imagination')
list_transcript.append('WoodyShaw_InACapricornianWay')
list_transcript.append('WoodyShaw_Rahsaan\'sRun')
list_transcript.append('WoodyShaw_Rosewood')
list_transcript.append('WoodyShaw_SteppingStone')
list_transcript.append('WoodyShaw_Steve\'sBlues')
list_transcript.append('WyntonKelly_FreddieTheFreeloader')
list_transcript.append('WyntonMarsalis_AprilInParis')
list_transcript.append('WyntonMarsalis_Caravan')
list_transcript.append('WyntonMarsalis_Cherokee')
list_transcript.append('WyntonMarsalis_CherokeeII')
list_transcript.append('WyntonMarsalis_JohnnyComeLately')
list_transcript.append('WyntonMarsalis_U.M.M.G.')
list_transcript.append('WyntonMarsalis_You\'reMyEverything')
list_transcript.append('ZootSims_AllTheThingsYouAre')
list_transcript.append('ZootSims_DancingInTheDark-1')
list_transcript.append('ZootSims_DancingInTheDark-2')
list_transcript.append('ZootSims_KingDavid')
list_transcript.append('ZootSims_NightAndDay-1')
list_transcript.append('ZootSims_NightAndDay-2')

###########################################

app = Flask(__name__)

@app.route('/')
def home_page():
	return render_template('home_page.html')

@app.route('/search')
def search():
#rechercher la grille d'un standard
	search_title = request.args.get('title','')
	if search_title:
		regex = re.compile(r'.*'+search_title+'.*',re.IGNORECASE)
		results_title = []
		selectobj = filter(regex.search, list_titles)
		for val in selectobj:
			results_title.append(val)
	else: 
		results_title = []
		
#rechercher un artiste
	search_artist = request.args.get('artist','')
	if search_artist:
		results_artist = []
		regex = re.compile(r'.*'+search_artist+'.*',re.IGNORECASE)
		selectobj = filter(regex.search, artist_list)
		for val in selectobj:
			results_artist.append(val)
	else:
		results_artist = []
			
#rechercher un relevé
	search_transcript = request.args.get('transcript','')
	if search_transcript:
		results_transcript = []
		regex = re.compile(r'.*'+search_transcript+'.*',re.IGNORECASE)
		selectobj = filter(regex.search, list_transcript)
		for val in selectobj:
			results_transcript.append(val)
	else: 
		results_transcript = []
		
#rechercher les versions d\'un standard
	search_versions = request.args.get('versions','')
	s = versions_search()
	s.init_versionsDB()
	if search_versions:
		results_versions = []
		regex = re.compile(r'.*'+search_versions+'.*',re.IGNORECASE)
		selectobj = filter(regex.search, s.DB.keys())
		for val in selectobj:
			results_versions.append(val)
	else: 
		results_versions = []

#rechercher une cadence
	search_cadence = request.args.get('cadence','')
	if search_cadence:
		results_cadence = []
		for x in list_cadence:
			y = re.findall('\\b'+search_cadence, x)
			if y != []:
				results_cadence += [(x,list_cadence.index(x)+1)]
				list_name = lists[list_cadence.index(x)+1]
	else:
		results_cadence = []
	
#rechercher un pont
	search_bridge = request.args.get('bridge','')
	if search_bridge:
		results_bridge = []
		for x in list_bridge:
			y = re.findall('\\b'+search_bridge, x)
			if y != []:
				results_bridge += [(x,list_bridge.index(x)+121)]
	else:
		results_bridge = []

#rechercher un article
	search_article = request.args.get('article','')
	if search_article:
		art = articles()
		art.init_articlesDB()
		results_article = []
		input_file = open('static/nbeniesDB.dict','r')
		read_file = input_file.read()
		regex = re.compile(r'{[^}]*'+search_article+'[^}]+}', re.IGNORECASE)
		result = re.findall(regex,read_file)
		regex2 = re.compile(r'\'titre\':([^\]]+\])')
		for i in result:
			result2 = re.findall(regex2,str(i))
		for i in result2:
			results_article += [(i,art.DB[i])]
		input_file.close()
	else:
		results_article = []
	return render_template('query_results.html', results_article=results_article, results_transcript=results_transcript, results_artist=results_artist, results_title=results_title, results_cadence=results_cadence, results_bridge=results_bridge, results_versions=results_versions)

@app.route('/artist')
def artist_search():
	search_artist = request.args.get('')
	
	alb = album()
	bio = biography()
	grp = groups()
	trk = tracks()
	mb = members()
	
	alb.init_albumDB()
	bio.init_biographyDB()
	grp.init_groupsDB()
	trk.init_tracksDB()
	mb.init_membersDB()
	
	bio_val = bio.DB[search_artist]
	grp_val = grp.DB[search_artist]
	alb_val = alb.DB[search_artist]
	
	#tree:root
	var_data = 'var data = [{"id": 1,"name": "Artist","description": "'+search_artist+'"},'
	
	#tree:level1
	var_data += '{"id": 2,"parentId": 1,"name": "Biography","description": "'+bio_val+'"},'
	var_data += '{"id": 3,"parentId": 1,"name": "Groups","description": "--expand--"},'
	var_data += '{"id": 4,"parentId": 1,"name": "Discography","description": "--expand--"},'
	
	#counter
	i = 4
	j = 4
	
	#tree:level2->Groups
	for val in grp_val:
		i = j
		i += 1
		j = i+1
		var_data += '{"id": '+str(i)+',"parentId": 3,"name":"Group","description": "'+val+'"},'
		#tree:level3->group members
		try:
			for val2 in mb.DB[val]:
				var_data += '{"id": '+str(j)+',"parentId": '+str(i)+',"name":"Group Members","description": "'+val2+'"},'
				j += 1
		except KeyError:
			pass
	
	#counter
	j = i

	#tree:level2->Discography
	for val in alb_val:
		i = j
		i += 1
		j = i+1
		var_data += '{"id": '+str(i)+',"parentId": 4,"name":"Album","description": "'+val+'"},'
		#tree:level3->Tracks
		try:
			for val2 in trk.DB[val]:
				var_data += '{"id": '+str(j)+',"parentId": '+str(i)+',"name":"Tracks","description": "'+val2+'"},'
				j += 1
		except KeyError:
			pass
			
	var_data += '];'
	
	return render_template('artist_results.html', var_data=var_data)

	
@app.route('/list')
def view_list():
	list_number = request.args.get('')
	f = open('static/lists/list'+list_number+'.html', encoding='ISO 8859-1')
	content = f.read()
	s = BeautifulSoup(content,'html.parser')
	title_list = []
	for y in s.findAll('a', href=True):
		g = open('static/corpus-list/'+y['href'], encoding='ISO 8859-1')
		content2 = g.read()
		t = BeautifulSoup(content2, 'html.parser')
		title = t.find('h4')
		if title:
			title_list += [(title.text,y['href'])]
			
	list_name=lists[int(re.findall(r'(\d+)',list_number)[0])-1]
	
	return render_template('list_results.html', title_list=title_list, list_name=list_name)
				
@app.route('/view/')
def view_theme():
	
#afficher la grille
	view_word = request.args.get('')
	f = open('static/corpus-html/'+view_word+'.html')
	plain = f.read()
	s = BeautifulSoup(plain, 'html.parser')
	title = s.find('h4').text
	title_encoded = urllib.parse.quote(title)
	results = []
	for corpus in s.findAll('pre'):
		results.append(corpus.text)

	return render_template('view_theme.html', results=results, title=title, title_encoded=title_encoded)
	
@app.route('/view_list/')
def list_display():
	view_link = request.args.get('')
	f = open('static/corpus-list/'+view_link)
	plain = f.read()
	s = BeautifulSoup(plain, 'html.parser')
	title = s.find('h4').text
	title_encoded = urllib.parse.quote(title)
	results = []
	span_chords = []
	
	for corpus in s.findAll('pre'):
		results.append(corpus.text)
		
	span_chords = s.findAll('span')[0]
	
	list_name=lists[int(re.findall(r'(\d+)',view_link)[0])-1]
	
	return render_template('view_theme.html', results=results, title=title, title_encoded=title_encoded, span_chords=span_chords, list_name=list_name)

@app.route('/versions')
def versions():
	versions_query = request.args.get('')
	s = versions_search()
	s.init_versionsDB()
	rvtmp1 = s.DB.get(versions_query)
	rvtmp2 = [x.replace('•','+') for x in rvtmp1]
	results_versions = zip(rvtmp1,rvtmp2)
	return render_template('view_versions.html',results_versions=results_versions)
	
@app.route('/transpose')
def transpose_theme():
	
	results = []
	
	tune_coded = request.args.get('tune','')
	tune = urllib.parse.unquote(tune_coded)
	tone = request.args.get('tone','')
	
	
	pitch_flat = ('A','Bb','Cb','C','Db','D','Eb','E','F','Gb','G','Ab')
	pitch_sharp = ('A','A#','B','C','C#','D','D#','E','F','F#','G','G#')
	
	tone_flat = ('C','F','Bb','Eb','Ab','Db','Gb','Cb')
	tone_sharp = ('A#','D#','G#','C#','F#','B','E','A','D','G')
	
	f = open('static/corpus-html/'+tune+'.html')
	plain = f.read()
	occ = plain.find('Key of ')
	key = plain[occ+7:occ+9].strip()
	key = key.strip('m')
	
	init_pitch = key
	final_pitch = tone

	#enharmonic choice
	if init_pitch in tone_flat:
		if final_pitch in tone_flat:
			index_init = pitch_flat.index(init_pitch)
			index_final = pitch_flat.index(final_pitch)
			diff = index_final - index_init
		elif final_pitch in tone_sharp:
			index_init = pitch_flat.index(init_pitch)
			index_final = pitch_sharp.index(final_pitch)
			diff = index_final - index_init
	elif init_pitch in tone_sharp:
		if final_pitch in tone_flat:
			index_init = pitch_sharp.index(init_pitch)
			index_final = pitch_flat.index(final_pitch)
			diff = index_final - index_init
		elif final_pitch in tone_sharp:
			index_init = pitch_sharp.index(init_pitch)
			index_final = pitch_sharp.index(final_pitch)
			diff = index_final - index_init
	
	corpus_list = []
	view_word = request.args.get('')
	f = open('static/corpus-html/'+tune+'.html')
	plain = f.read()
	s = BeautifulSoup(plain, 'html.parser')
	title = s.find('h4').text
	title_encoded = urllib.parse.quote(title)
	for corpus in s.findAll('pre'):
		corpus_list.append(corpus.text)

	chord_flat = set(re.findall(r'[ABCDEFG]b+', str(corpus_list)))
	chord_sharp = set(re.findall(r'[ABCDEFG]#+', str(corpus_list)))
	chord_none = set(re.findall(r'[ABCDEFG](?!b|#)+', str(corpus_list)))
	
	if chord_flat:
		for x in chord_flat:
			corpus_list = [y.replace(x,'*'+x) for y in corpus_list]
	if chord_sharp:
		for x in chord_sharp:
			corpus_list = [y.replace(x,'*'+x) for y in corpus_list]
	if chord_none:
		for x in chord_none:
			corpus_list = [y.replace(x,'*'+x) for y in corpus_list]

#transposition			
	if chord_flat:
		for x in chord_flat:
			z = pitch_flat.index(x)
			q = z + diff
			pattern = re.compile(r'(\*\*|\*)'+ re.escape(x))
			if q <= 11:
				corpus_list = [re.sub(pattern,pitch_flat[q],y) for y in corpus_list]
			else:
				corpus_list = [re.sub(pattern,pitch_flat[q-12],y) for y in corpus_list]

	if chord_sharp:
		for x in chord_sharp:
			z = pitch_sharp.index(x)
			q = z + diff
			pattern = re.compile(r'(\*\*|\*)'+ re.escape(x))
			if q <= 11:
				corpus_list = [re.sub(pattern,pitch_flat[q],y) for y in corpus_list]
			else:
				corpus_list = [re.sub(pattern,pitch_flat[q-12],y) for y in corpus_list]

	if chord_none:
		for x in chord_none:
			if final_pitch in tone_flat:
				try:
					z = pitch_flat.index(x)
				except ValueError:
					z = pitch_sharp.index(x)
				q = z + diff
				pattern_none = re.compile(r'\*'+re.escape(x)+'(?!b|#)+')
				if q <= 11:
					corpus_list = [re.sub(pattern_none,pitch_flat[q],y) for y in corpus_list]
				else:
					corpus_list = [re.sub(pattern_none,pitch_flat[q-12],y) for y in corpus_list]
			elif final_pitch in tone_sharp:
				try:
					z = pitch_sharp.index(x)
				except ValueError:
					z = pitch_flat.index(x)
				q = z + diff
				pattern_none = re.compile(r'\*'+re.escape(x)+'(?!b|#)+')
				if q <= 11:
					corpus_list = [re.sub(pattern_none,pitch_sharp[q],y) for y in corpus_list]
				else:
					corpus_list = [re.sub(pattern_none,pitch_sharp[q-12],y) for y in corpus_list]

	for text_in_corpus in corpus_list:
		results.append(text_in_corpus)
	
	return render_template('view_theme.html', results=results, title=title, title_encoded=title_encoded)

