# -*- coding: utf-8 -*-

import re
from flask import Flask, request, render_template
from bs4 import BeautifulSoup

list_titles = []
list_titles.append('AFTER YOU-VE GONE')
list_titles.append('AIN-T MISBEHAVIN')
list_titles.append('AIREGIN')
list_titles.append('AIR MAIL SPECIAL')
list_titles.append('ALEXANDER-S RAGTIME BAND')
list_titles.append('ALL BLUES')
list_titles.append('ALL GOD-S CHILDREN GOT RHYTHM')
list_titles.append('ALL OF ME')
list_titles.append('ALL OF YOU')
list_titles.append('ALL THE THINGS YOU ARE')
list_titles.append('ALMOST LIKE BEING IN LOVE')
list_titles.append('ALONE TOGETHER')
list_titles.append('ALONG CAME BETTY')
list_titles.append('ALWAYS')
list_titles.append('AMAZING GRACE')
list_titles.append('AM I BLUE')
list_titles.append('ANGEL EYES')
list_titles.append('ANYTHING GOES')
list_titles.append('APRIL IN PARIS')
list_titles.append('AREN-T YOU GLAD YOU-RE YOU')
list_titles.append('AS LONG AS I LIVE')
list_titles.append('AS TIME GOES BY')
list_titles.append('AT SUNDOWN')
list_titles.append('AUTUMN IN NEW YORK')
list_titles.append('AUTUMN LEAVES')
list_titles.append('AVALON')
list_titles.append('AZURE')
list_titles.append('BASIN STREET BLUES')
list_titles.append('BAUBLES BANGLES AND BEADS')
list_titles.append('BEAUTIFUL LOVE')
list_titles.append('BERNIE-S TUNE')
list_titles.append('BETWEEN THE DEVIL AND THE DEEP BLUE SEA')
list_titles.append('BEWITCHED BOTHERED AND BEWILDERED')
list_titles.append('BIDIN MY TIME')
list_titles.append('BILL BAILEY')
list_titles.append('BIRTH OF THE BLUES')
list_titles.append('BLACK AND BLUE')
list_titles.append('BLACK COFFEE')
list_titles.append('BLUE BOSSA')
list_titles.append('BLUE LOU')
list_titles.append('BLUE MONK ')
list_titles.append('BLUE MOON')
list_titles.append('BLUE ROOM (THE)')
list_titles.append('BLUESETTE')
list_titles.append('BLUE SKIES')
list_titles.append('BODY AND SOUL')
list_titles.append('BORN TO BE BLUE')
list_titles.append('BROADWAY')
list_titles.append('BUT BEAUTIFUL')
list_titles.append('BUT NOT FOR ME')
list_titles.append('BYE BYE BLACKBIRD')
list_titles.append('BYE BYE BLUES')
list_titles.append('BY MYSELF')
list_titles.append('CABIN IN THE SKY')
list_titles.append('CAN-T GET OUT OF THIS MOOD')
list_titles.append('CAN-T HELP LOVIN DAT MAN')
list_titles.append('CAN-T WE BE FRIENDS')
list_titles.append('CARAVAN')
list_titles.append('CARNIVAL (BLACK ORPHEUS)')
list_titles.append('CHEEK TO CHEEK')
list_titles.append('CHELSEA BRIDGE')
list_titles.append('CHEROKEE')
list_titles.append('CHICAGO')
list_titles.append('CHRISTMAS SONG')
list_titles.append('COME RAIN OR COME SHINE')
list_titles.append('COMES LOVE')
list_titles.append('CONFIRMATION')
list_titles.append('COTTAGE FOR SALE')
list_titles.append('COTTON TAIL')
list_titles.append('CRAZY RHYTHM')
list_titles.append('CRY ME A RIVER')
list_titles.append('CUTE')
list_titles.append('DANCING IN THE DARK')
list_titles.append('DANCING ON THE CEILING')
list_titles.append('DANNY BOY')
list_titles.append('DARN THAT DREAM')
list_titles.append('DAY BY DAY')
list_titles.append('DAY IN  DAY OUT')
list_titles.append('DAYS OF WINE AND ROSES')
list_titles.append('DEARLY BELOVED')
list_titles.append('DEED I DO')
list_titles.append('DEEP PURPLE')
list_titles.append('DESAFINADA')
list_titles.append('DJANGO')
list_titles.append('DO NOTHIN TILL YOU HEAR FROM ME')
list_titles.append('DON-T BLAME ME')
list_titles.append('DON-T GET AROUND MUCH ANY MORE')
list_titles.append('DON-T TAKE YOUR LOVE FROM ME')
list_titles.append('DOXY')
list_titles.append('EAST OF THE SUN')
list_titles.append('EASY LIVIN')
list_titles.append('EASY TO LOVE')
list_titles.append('EMBRACEABLE YOU')
list_titles.append('END OF A LOVE AFFAIR (THE)')
list_titles.append('EPISTROPHY')
list_titles.append('EVERYTHING HAPPENS TO ME')
list_titles.append('EVERYTHING I-VE GOT BELONGS TO YOU')
list_titles.append('EV-RY TIME WE SAY GOODBY')
list_titles.append('EXACTLY LIKE YOU')
list_titles.append('FALLING IN LOVE WITH LOVE')
list_titles.append('FASCINATING RHYTHM')
list_titles.append('FINE AND DANDY')
list_titles.append('FINE ROMANCE (A)')
list_titles.append('FLY ME TO THE MOON')
list_titles.append('FOGGY DAY (A)')
list_titles.append('FOLKS WHO LIVE ON THE HILL')
list_titles.append('FOOLS RUSH IN')
list_titles.append('FOR ALL WE KNOW')
list_titles.append('FOUR')
list_titles.append('FREDDIE THE FREELOADER')
list_titles.append('FROM THIS MOMENT ON')
list_titles.append('GAL IN CALICO')
list_titles.append('GEE BABY AIN-T I GOOD TO YOU')
list_titles.append('GEORGIA ON MY MIND')
list_titles.append('GET HAPPY')
list_titles.append('GET OUT OF TOWN')
list_titles.append('GHOST OF A CHANCE WITH YOU')
list_titles.append('GIANT STEPS')
list_titles.append('GIRL FROM IPANEMA')
list_titles.append('GIVE ME THE SIMPLE LIFE')
list_titles.append('GLAD TO BE UNHAPPY')
list_titles.append('GOD BLESS THE CHILD')
list_titles.append('GONE WITH THE WIND')
list_titles.append('GREEN DOLPHIN STREET')
list_titles.append('GROOVIN HIGH')
list_titles.append('HALLELUJAH')
list_titles.append('HAVE YOU MET MISS JONES')
list_titles.append('HEAT WAVE')
list_titles.append('HERE-S THAT RAINY DAY')
list_titles.append('HONEYSUCKLE ROSE')
list_titles.append('HOW ABOUT YOU')
list_titles.append('HOW DEEP IS THE OCEAN')
list_titles.append('HOW HIGH THE MOON')
list_titles.append('HOW INSENSITIVE')
list_titles.append('HOW LONG HAS THIS BEEN GOING ON')
list_titles.append('I CAN-T BELIEVE THAT YOUR IN LOVE')
list_titles.append('I CAN-T GET STARTED WITH YOU')
list_titles.append('I CAN-T GIVE YOU ANYTHING BUT LOVE')
list_titles.append('I CONCENTRATE ON YOU')
list_titles.append('I COULD WRITE A BOOK')
list_titles.append('I COVER THE WATERFRONT')
list_titles.append('IDAHO')
list_titles.append('I DIDN-T KNOW WHAT TIME IT WAS')
list_titles.append('I DON-T KNOW WHY')
list_titles.append('I FALL IN LOVE TOO EASILY')
list_titles.append('IF I HAD YOU')
list_titles.append('IF I LOVE AGAIN')
list_titles.append('IF I SHOULD LOSE YOU')
list_titles.append('IF I WERE A BELL')
list_titles.append('I FOUND A NEW BABY')
list_titles.append('IF THERE IS SOMEONE LOVELIER')
list_titles.append('IF YOU COULD SEE ME NOW')
list_titles.append('I GET A KICK OUT OF YOU')
list_titles.append('I GOT IT BAD AND THAT AIN-T GOOD')
list_titles.append('I GOT RHYTHM')
list_titles.append('I HADN-T ANYONE -TIL YOU')
list_titles.append('I HEAR A RHAPSODY')
list_titles.append('I HEAR MUSIC')
list_titles.append('I LEFT MY HEART IN SAN FRANCISCO')
list_titles.append('I LET A SONG GO OUT  OF MY HEART')
list_titles.append('I-LL BE AROUND')
list_titles.append('I-LL BE SEEING YOU')
list_titles.append('I-LL GET BY')
list_titles.append('I-LL NEVER BE THE SAME')
list_titles.append('I-LL REMEMBER APRIL')
list_titles.append('I-LL STRING ALONG WITH YOU')
list_titles.append('I-LL TAKE MANHATTAN')
list_titles.append('I-LL TAKE ROMANCE')
list_titles.append('ILL WIND')
list_titles.append('I LOVE PARIS')
list_titles.append('I LOVE YOU')
list_titles.append('IMAGINATION')
list_titles.append('I MAY BE WRONG')
list_titles.append('I-M BEGINNING TO SEE THE LIGHT')
list_titles.append('I-M CONFESSIN')
list_titles.append('I-M GETTIN SENTIMENTAL OVER YOU')
list_titles.append('I-M GLAD THERE IS YOU')
list_titles.append('I-M IN THE MOOD FOR LOVE')
list_titles.append('I-M OLD FASHIONED')
list_titles.append('IN A MELLOW TONE')
list_titles.append('IN A SENTIMENTAL MOOD')
list_titles.append('INDIANA')
list_titles.append('INDIAN SUMMER')
list_titles.append('I NEVER KNEW')
list_titles.append('IN MY SOLITUDE')
list_titles.append('INVITATION')
list_titles.append('IN YOUR OWN SWEET WAY')
list_titles.append('I REMEMBER YOU')
list_titles.append('I SHOULD CARE')
list_titles.append('ISN-T IT ROMANTIC')
list_titles.append('I SURRENDER DEAR')
list_titles.append('IT COULD HAPPEN TO YOU')
list_titles.append('IT DON-T MEAN A THING')
list_titles.append('IT HAD TO BE YOU')
list_titles.append('I THOUGHT ABOUT YOU')
list_titles.append('IT MIGHT AS WELL BE SPRING')
list_titles.append('IT NEVER ENTERED MY MIND')
list_titles.append('IT-S ALL RIGHT WITH ME')
list_titles.append('IT-S ONLY A PAPER MOON')
list_titles.append('IT-S THE TALK OF THE TOWN')
list_titles.append('IT-S YOU OR NO ONE')
list_titles.append('IT WAS JUST ONE OF THOSE THINGS')
list_titles.append('I-VE GOT A CRUSH ON YOU')
list_titles.append('I-VE GOT MY LOVE TO KEEP ME WARM')
list_titles.append('I-VE GOT THE WORLD ON A STRING')
list_titles.append('I-VE GOT YOU UNDER MY SKIN')
list_titles.append('I-VE GROWN ACCUSTOMED TO YOUR FACE')
list_titles.append('I WANT TO BE HAPPY')
list_titles.append('I WISH I WERE IN LOVE AGAIN')
list_titles.append('I WON-T DANCE')
list_titles.append('JEEPERS  CREEPERS')
list_titles.append('JORDU')
list_titles.append('JOY SPRING')
list_titles.append('JUST FRIENDS')
list_titles.append('JUST IN TIME')
list_titles.append('JUST SQUEEZE ME')
list_titles.append('JUST YOU JUST ME')
list_titles.append('LADY BE GOOD')
list_titles.append('LADY BIRD')
list_titles.append('LADY IN RED  (THE)')
list_titles.append('LADY IS A TRAMP (THE)')
list_titles.append('LAST TIME I SAW PARIS (THE)')
list_titles.append('LAURA')
list_titles.append('LAZYBIRD')
list_titles.append('LET-S FACE THE MUSIC AND DANCE')
list_titles.append('LIKE SOMEONE IN LOVE')
list_titles.append('LIL DARLIN')
list_titles.append('LIMEHOUSE BLUES')
list_titles.append('LITTLE WHITE LIES')
list_titles.append('LIZA')
list_titles.append('LONG AGO AND FAR AWAY')
list_titles.append('LOOK FOR THE SILVER LINING')
list_titles.append('LOOKING FOR A BOY')
list_titles.append('LOVE FOR SALE')
list_titles.append('LOVE ME OR LEAVE ME')
list_titles.append('LOVE NEST (THE)')
list_titles.append('LOVER COME BACK TO ME')
list_titles.append('LOVER')
list_titles.append('LOVER MAN')
list_titles.append('LOVE WALKED IN')
list_titles.append('LULLABY IN RHYTHM')
list_titles.append('LULLABY OF BIRDLAND')
list_titles.append('LULLABY OF BROADWAY')
list_titles.append('LULLABY OF THE LEAVES')
list_titles.append('MAKIN WHOOPEE')
list_titles.append('MAN I LOVE  (THE)')
list_titles.append('MEAN TO ME')
list_titles.append('MEDITATION')
list_titles.append('MEMORIES OF YOU')
list_titles.append('MISTY')
list_titles.append('MOOD  INDIGO')
list_titles.append('MOONGLOW')
list_titles.append('MOONLIGHT IN VERMONT')
list_titles.append('MORE I SEE YOU (THE)')
list_titles.append('MORE THAN YOU KNOW')
list_titles.append('MOUNTAIN GREENERY')
list_titles.append('MY BLUE HEAVEN')
list_titles.append('MY FAVORITE THINGS')
list_titles.append('MY FOOLISH HEART')
list_titles.append('MY FUNNY VALENTINE')
list_titles.append('MY HEART BELONGS TO DADDY')
list_titles.append('MY HEART STOOD STILL')
list_titles.append('MY IDEAL')
list_titles.append('MY MELANCHOLY BABY')
list_titles.append('MY OLD FLAME')
list_titles.append('MY ONE AND ONLY LOVE')
list_titles.append('MY ROMANCE')
list_titles.append('MY SHINING HOUR')
list_titles.append('MY SHIP')
list_titles.append('MY SILENT LOVE')
list_titles.append('NEARNESS OF YOU (THE)')
list_titles.append('NICE WORK IF YOU CAN GET IT')
list_titles.append('NIGHT AND DAY')
list_titles.append('NIGHT IN TUNISIA')
list_titles.append('NOBODY ELSE BUT ME')
list_titles.append('NO MOON AT ALL')
list_titles.append('OLD DEVIL MOON')
list_titles.append('ON A CLEAR DAY')
list_titles.append('ON A SLOW BOAT TO CHINA')
list_titles.append('ONCE IN A WHILE')
list_titles.append('ONE I LOVE BELONGS TO SOMEBODY')
list_titles.append('ONE NOTE SAMBA')
list_titles.append('ON THE STREET WHERE YOU LIVE')
list_titles.append('ON THE SUNNY SIDE OF THE STREET')
list_titles.append('OUR DAY WILL COME')
list_titles.append('OUR LOVE IS HERE TO STAY')
list_titles.append('OUT OF NOWHERE')
list_titles.append('OUT OF THIS WORLD')
list_titles.append('OVER THE RAINBOW')
list_titles.append('PENNIES FROM HEAVEN')
list_titles.append('PEOPLE WILL SAY WE-RE IN LOVE')
list_titles.append('PERDIDO')
list_titles.append('PICK YOURSELF UP')
list_titles.append('POLKA DOTS AND MOONBEAMS')
list_titles.append('POOR BUTTERFLY')
list_titles.append('PORTRAIT OF JENNIE (A)')
list_titles.append('PRELUDE TO A KISS')
list_titles.append('QUIET NIGHTS OF QUIET STARS')
list_titles.append('RECORDAME')
list_titles.append('ROSE ROOM')
list_titles.append('ROSETTA')
list_titles.append('ROUND MIDNIGHT')
list_titles.append('RUBY MY DEAR')
list_titles.append('SAMBA DE ORFEU')
list_titles.append('SATIN DOLL')
list_titles.append('SAVOY BLUES')
list_titles.append('SCRAPPLE FROM THE APPLE')
list_titles.append('SECRET LOVE')
list_titles.append('SEPTEMBER IN THE RAIN')
list_titles.append('SEPTEMBER SONG')
list_titles.append('SEVEN COME ELEVEN')
list_titles.append('SHADOW OF YOUR SMILE')
list_titles.append('SHE-S FUNNY THAT WAY')
list_titles.append('SHINY STOCKINGS')
list_titles.append('SKYLARK')
list_titles.append('SMOKE GETS IN YOUR EYES')
list_titles.append('SOFTLY AS IN A MORNING SUNRISE')
list_titles.append('SO IN LOVE')
list_titles.append('SOLAR')
list_titles.append('SOMEBODY LOVES ME')
list_titles.append('SOMEDAY MY PRINCE WILL COME')
list_titles.append('SOMEONE TO WATCH OVER ME')
list_titles.append('SOMETIMES I-M HAPPY')
list_titles.append('SONG IS YOU (THE)')
list_titles.append('SOON')
list_titles.append('SOPHISTICATED LADY')
list_titles.append('SO WHAT')
list_titles.append('SPEAK LOW')
list_titles.append('S-POSIN')
list_titles.append('SPRING IS HERE')
list_titles.append('STARDUST')
list_titles.append('STAR EYES')
list_titles.append('STARS FELL ON ALABAMA')
list_titles.append('STELLA BY STARLIGHT')
list_titles.append('ST JAMES INFIRMARY BLUES')
list_titles.append('ST LOUIS BLUES')
list_titles.append('STOMPIN AT THE SAVOY')
list_titles.append('STORMY WEATHER')
list_titles.append('STREET OF DREAMS')
list_titles.append('STRIKE UP THE BAND')
list_titles.append('ST THOMAS')
list_titles.append('SUGAR')
list_titles.append('SUMMERTIME')
list_titles.append('SWEET AND LOVELY')
list_titles.append('SWEET GEORGIA BROWN')
list_titles.append('SWEETHEARTS ON PARADE')
list_titles.append('SWEET LORRAINE')
list_titles.append('SWINGING ON A STAR')
list_titles.append('S WONDERFUL')
list_titles.append('TAKE FIVE')
list_titles.append('TAKE THE A TRAIN')
list_titles.append('TAKING A CHANCE ON LOVE')
list_titles.append('TANGERINE')
list_titles.append('TEA FOR TWO')
list_titles.append('TENDERLY')
list_titles.append('THAT OLD FEELING')
list_titles.append('THERE IS NO GREATER LOVE')
list_titles.append('THERE-S A SMALL HOTEL')
list_titles.append('THERE WILL NEVER BE ANOTHER YOU')
list_titles.append('THESE FOOLISH THINGS')
list_titles.append('THEY ALL LAUGHED')
list_titles.append('THEY CAN-T TAKE THAT AWAY')
list_titles.append('THINGS AIN-T WHAT THEY USED TO BE')
list_titles.append('THIS CAN-T BE LOVE')
list_titles.append('THIS YEARS KISSES')
list_titles.append('THOU SWELL')
list_titles.append('THREE LITTLE WORDS')
list_titles.append('TIME AFTER TIME')
list_titles.append('TOO MARVELOUS FOR WORDS')
list_titles.append('TOUCH OF YOUR LIPS (THE)')
list_titles.append('TRY A LITTLE TENDERNESS')
list_titles.append('TUNE UP')
list_titles.append('TWO SLEEPY PEOPLE')
list_titles.append('UNDECIDED')
list_titles.append('UNTIL THE REAL THING COMES ALONG')
list_titles.append('UP A LAZY RIVER')
list_titles.append('VERY THOUGHT OF YOUTHE')
list_titles.append('WAIT TILL YOU SEE HER')
list_titles.append('WAVE')
list_titles.append('WAY YOU LOOK TONIGHT (THE)')
list_titles.append('WELL YOU NEEDN-T')
list_titles.append('WHAT A DIFFERENCE A DAY MADE')
list_titles.append('WHAT A LITTLE MOONLIGHT CAN DO')
list_titles.append('WHAT IS THERE TO SAY')
list_titles.append('WHAT IS THIS THING CALLED LOVE')
list_titles.append('WHAT-LL I DO')
list_titles.append('WHAT-S NEW')
list_titles.append('WHEN I FALL IN LOVE')
list_titles.append('WHEN SUNNY GETS BLUE')
list_titles.append('WHEN THE SAINTS GO MARCHING IN')
list_titles.append('WHEN YOUR LOVER HAS GONE')
list_titles.append('WHEN YOU WISH UPON A STAR')
list_titles.append('WHERE OR WHEN')
list_titles.append('WHIFFENPOOF SONG')
list_titles.append('WHISPERING')
list_titles.append('WHITE CHRISTMAS')
list_titles.append('WHO CARES')
list_titles.append('WHY SHOULDN-T I')
list_titles.append('WILLOW WEEP FOR ME')
list_titles.append('WITH THE WIND AND THE RAIN')
list_titles.append('WORLD IS WAITING FOR THE SUNRISE')
list_titles.append('WRAP YOUR TROUBLES IN DREAMS')
list_titles.append('YARDBIRD SUITE')
list_titles.append('YESTERDAY')
list_titles.append('YESTERDAYS')
list_titles.append('YOU AND THE NIGHT AND THE MUSIC')
list_titles.append('YOU BROUGHT A NEW KIND OF LOVE')
list_titles.append('YOU-D BE SO NICE TO COME HOME TO')
list_titles.append('YOU DON-T KNOW WHAT LOVE IS')
list_titles.append('YOU DO SOMETHING TO ME')
list_titles.append('YOU GO TO MY HEAD')
list_titles.append('YOURS IS MY HEART ALONE')
list_titles.append('YOU SAY YOU CARE')
list_titles.append('YOU STEPPED OUT OF A DREAM')
list_titles.append('YOU TOOK ADVANTAGE OF ME')
list_titles.append('ZING WENT THE STRINGS')

app = Flask(__name__)

@app.route('/title/')
def search_theme():
	search_word = request.args.get('')
	regex = re.compile(r'.*'+search_word+'.*',re.IGNORECASE)
	results = []
	selectobj = filter(regex.search, list_titles)
	for val in selectobj:
		results.append(val)
	return render_template('query_results.html', results=results)
	
@app.route('/view/')
def view_theme():
	view_word = request.args.get('')
	f = open('/home/jericho/Bureau/jmlDB/corpus-html/'+view_word+'.html')
	plain = f.read()
	s = BeautifulSoup(plain, 'html.parser')
	title = s.find('h4')
	title = title.text
	results = []
	for corpus in s.findAll('pre'):
		results.append(corpus.text)
	return render_template('view_theme.html', results=results, title=title)

