nbenies_title_url_dict = {
'[Rendez-vous à Crest]':'http://soufflebleu.fr/2019/07/29/rendez-vous-a-crest/',
'[Jazz ? Rencontre(s) avec Derek Bailey]':'http://soufflebleu.fr/2019/07/12/jazz-rencontres-avec-derek-bailey/',
'[Jazz, le passé dans le présent.]':'http://soufflebleu.fr/2019/06/08/jazz-le-passe-dans-le-present/',
'[De retour de festival]':'http://soufflebleu.fr/2019/06/04/de-retour-de-festival/',
'[A l’Institut du Monde Arabe (IMA), les « Arabofolies »]':'http://soufflebleu.fr/2019/05/28/a-linstitut-du-monde-arabe-ima-les-arabofolies/',
'[Quel avenir pour la construction européenne ?]':'http://soufflebleu.fr/2019/05/27/quel-avenir-pour-la-construction-europeenne/',
'[Les mémoires et leur dépassement]':'http://soufflebleu.fr/2019/05/27/les-memoires-et-leur-depassement/',
'[Bihr, deuxième !]':'http://soufflebleu.fr/2019/05/27/bihr-deuxieme/',
'[Débarquement, 75e ! Un travail de mémoire]':'http://soufflebleu.fr/2019/05/20/debarquement-75e-un-travail-de-memoire/',
'[Jazz, Soul Jazz Rebels]':'http://soufflebleu.fr/2019/04/18/jazz-soul-jazz-rebels/',
'[Jazz, Shauli Einav]':'http://soufflebleu.fr/2019/04/18/jazz-shauli-einav/',
'[Jazz, Laurent Dehors Trio]':'http://soufflebleu.fr/2019/04/18/jazz-laurent-dehors-trio/',
'[Jazz, Hugo Corbin]':'http://soufflebleu.fr/2019/04/18/jazz-hugo-corbin/',
'[Jazz vocal, Naysing]':'http://soufflebleu.fr/2019/04/06/jazz-vocal-naysing/',
'[Jazz, Un Zoo de liberté ?]':'http://soufflebleu.fr/2019/04/06/jazz-un-zoo-de-liberte/',
'[Le jazz dans toutes ses facettes.]':'http://soufflebleu.fr/2019/04/05/le-jazz-dans-toutes-ses-facettes/',
'[JAZZ, bassiste et saxophoniste dans la mêlée]':'http://soufflebleu.fr/2019/04/05/jazz-bassiste-et-saxophoniste-dans-la-melee/',
'[Jazz]':'http://soufflebleu.fr/2019/03/28/jazz-8/',
'[Jazz, Dave Rempis et son label Aerophonic]':'http://soufflebleu.fr/2019/02/23/jazz-dave-rempis-et-son-label-aerophonic/',
'[JAZZ, Michel Fernandez quartet]':'http://soufflebleu.fr/2019/02/21/jazz-michel-fernandez-quartet/',
'[Des batteurs à voir pour rêver]':'http://soufflebleu.fr/2019/02/09/des-batteurs-a-voir-pour-rever/',
'[Mémoires]':'http://soufflebleu.fr/2018/12/23/memoires/',
'[Du Nord et du Sud]':'http://soufflebleu.fr/2018/12/23/du-nord-et-du-sud/',
'[Des cadeaux à (se) faire pour vos fêtes et pas forcément pour les Fêtes !]':'http://soufflebleu.fr/2018/12/23/des-cadeaux-a-se-faire-pour-vos-fetes-et-pas-forcement-pour-les-fetes/',
'[Confrontation]':'http://soufflebleu.fr/2018/12/23/confrontation/',
'[Rencontres (3)]':'http://soufflebleu.fr/2018/12/04/rencontres-3/',
'[Rencontres (2)]':'http://soufflebleu.fr/2018/12/04/rencontres-2/',
'[Rencontres (1)]':'http://soufflebleu.fr/2018/12/04/rencontres-1/',
'[Jazz. Reggie Washington, contrebassiste, renoue avec l’acoustique]':'http://soufflebleu.fr/2018/12/02/jazz-reggie-washington-contrebassiste-renoue-avec-lacoustique/',
'[Jazz. Edward Perraud, batteur, renoue avec le concept d’album.]':'http://soufflebleu.fr/2018/12/02/jazz-edward-perraud-batteur-renoue-avec-le-concept-dalbum/',
'[Jean-Pascal Moget Trio]':'http://soufflebleu.fr/2018/10/29/jean-pascal-moget-trio/',
'[Stéphane Kerecki se dévoile.]':'http://soufflebleu.fr/2018/10/26/stephane-kerecki-se-devoile/',
'[Samuel Blaser et le blues]':'http://soufflebleu.fr/2018/10/24/samuel-blaser-et-le-blues/',
'[Stan Getz, le retour]':'http://soufflebleu.fr/2018/10/23/stan-getz-le-retour/',
'[Ray Charles vivant.]':'http://soufflebleu.fr/2018/10/23/ray-charles-vivant/',
'[Jazz. Quand un lion rencontre un tigre…]':'http://soufflebleu.fr/2018/10/23/jazz-quand-un-lion-rencontre-un-tigre/',
'[Le jazz en cette rentrée]':'http://soufflebleu.fr/2018/10/21/le-jazz-en-cette-rentree/',
'[A une femme libre : la baronne Nica de Koenigswarter]':'http://soufflebleu.fr/2018/10/15/a-une-femme-libre-la-baronne-nica-de-koenigswarter/',
'[UNE VIE DANS LE SIÈCLE. Compléments au «\xa0souffle de la révolte\xa0»]':'http://soufflebleu.fr/2018/10/14/une-vie-dans-le-siecle-complements-au-souffle-de-la-revolte/',
'[Jazz  Fincker/Touery quartet]':'http://soufflebleu.fr/2018/09/24/jazz-fincker-touery-quartet/',
'[Jazz, Une grande chanteuse, Cecile McLorin Salvant. Un grand orchestre.]':'http://soufflebleu.fr/2018/09/18/jazz-une-grande-chanteuse-cecile-mclorin-salvant-un-grand-orchestre/',
'[Jazz, Hubert Dupont en réseau]':'http://soufflebleu.fr/2018/09/14/jazz-hubert-dupont-en-reseau/',
'[Jazz et écriture automatique]':'http://soufflebleu.fr/2018/09/05/jazz-et-ecriture-automatique/',
'[Jazz, François Bernat et Miles]':'http://soufflebleu.fr/2018/09/03/jazz-francois-bernat-et-miles/',
'[A Crest pour le festival et une série de conférences sur deux villes, Kansas City et Detroit]':'http://soufflebleu.fr/2018/07/30/a-crest-pour-le-festival-et-une-serie-de-conferences-sur-deux-villes-kansas-city-et-detroit/',
'[Compléments au «\xa0souffle de la révolte\xa0»]':'http://soufflebleu.fr/2018/07/24/complements-au-souffle-de-la-revolte-3/',
'[John Coltrane : Retour vers le futur.]':'http://soufflebleu.fr/2018/07/18/john-coltrane-retour-vers-le-futur/',
'[JAZZ. FESTIVALS IMMOBILES (2)]':'http://soufflebleu.fr/2018/07/14/jazz-festivals-immobiles-2/',
'[JAZZ. Festivals immobiles (1)]':'http://soufflebleu.fr/2018/07/14/jazz-festivals-immobiles-1/',
'[Festival immobile avec Denis Fournier]':'http://soufflebleu.fr/2018/07/14/festival-immobile-avec-denis-fournier/',
'[Une saga américaine écrite par un Anglais]':'http://soufflebleu.fr/2018/07/04/une-saga-americaine-ecrite-par-un-anglais/',
'[Jazz, une musique qui n’oublie rien.]':'http://soufflebleu.fr/2018/06/15/jazz-une-musique-qui-noublie-rien/',
'[Compléments au «\xa0souffle de la révolte\xa0», une saga de Ray Celestin]':'http://soufflebleu.fr/2018/06/04/complements-au-souffle-de-la-revolte-une-saga-de-ray-celestin/',
'[Compléments au «\xa0souffle de la révolte\xa0», une photo]':'http://soufflebleu.fr/2018/06/04/complements-au-souffle-de-la-revolte-une-photo/',
'[Jazz teinté de pop]':'http://soufflebleu.fr/2018/06/03/jazz-teinte-de-pop/',
'[Jazz, Dave Liebman, rencontre au sommet]':'http://soufflebleu.fr/2018/06/03/jazz-dave-liebman-rencontre-au-sommet/',
'[Jazz, quand le pianiste s’appelle Kenny Barron…]':'http://soufflebleu.fr/2018/05/27/jazz-quand-le-pianiste-sappelle-kenny-barron/',
'[Jazz peut-être pour une musicienne aux influences multiples]':'http://soufflebleu.fr/2018/05/24/jazz-peut-etre-pour-une-musicienne-aux-influences-multiples/',
'[Jazz, Whirlwind – un label indépendant -]':'http://soufflebleu.fr/2018/04/29/jazz-whirlwind-un-label-independant/',
'[jazz, Deux pianistes, deux mondes]':'http://soufflebleu.fr/2018/04/29/jazz-deux-pianistes-deux-mondes/',
'[Un intitulé étrange, « Jazz From Carnegie Hall »]':'http://soufflebleu.fr/2018/04/26/un-intitule-etrange-jazz-from-carnegie-hall/',
'[La saga du siècle, du jazz et de Louis Armstrong, volume 15]':'http://soufflebleu.fr/2018/04/26/la-saga-du-siecle-du-jazz-et-de-louis-armstrong-volume-15/',
'[JAZZ, Cecil Taylor, départ pour l’éternité.]':'http://soufflebleu.fr/2018/04/17/jazz-cecil-taylor-depart-pour-leternite/',
'[JAZZ, Walter Smith III, saxophone ténor, propose sa relecture des classiques]':'http://soufflebleu.fr/2018/04/14/jazz-walter-smith-iii-saxophone-tenor-propose-sa-relecture-des-classiques/',
'[JAZZ, Sarrazy & Rochelle]':'http://soufflebleu.fr/2018/04/14/jazz-sarrazy-rochelle/',
'[Eric Dolphy, enfin !]':'http://soufflebleu.fr/2018/04/14/eric-dolphy-enfin/',
'[Un essai de Laurent Cugny]':'http://soufflebleu.fr/2018/04/13/un-essai-de-laurent-cugny/',
'[JAZZ, Henri Texier]':'http://soufflebleu.fr/2018/04/08/jazz-7/',
'[JAZZ, Théo Ceccaldi]':'http://soufflebleu.fr/2018/04/08/jazz-6/',
'[JAZZ, Cholet & Darche]':'http://soufflebleu.fr/2018/04/08/jazz-5/',
'[JAZZ, De Bechet à Jaspar]':'http://soufflebleu.fr/2018/04/08/jazz-4/',
'[Jazz, Julian Lage]':'http://soufflebleu.fr/2018/03/29/jazz-julian-lage/',
'[La renaissance de Harlem]':'http://soufflebleu.fr/2018/03/22/la-renaissance-de-harlem/',
'[UP Jazz dernière pour l’année 2017-2018, le 21 mars, jour d’arrivée théorique du printemps.]':'http://soufflebleu.fr/2018/03/21/up-jazz-derniere-pour-lannee-2017-2018-le-21-mars-jour-darrivee-theorique-du-printemps/',
'[UP Jazz du 7 mars 2018, La Côte Ouest au féminin]':'http://soufflebleu.fr/2018/03/07/up-jazz-du-7-mars-2018/',
'[Un simple trio…]':'http://soufflebleu.fr/2018/02/06/un-simple-trio/',
'[En attendant «\xa0Le souffle de la révolte\xa0», des compléments]':'http://soufflebleu.fr/2018/02/04/attendant-souffle-de-revolte-complements/',
'[En attendant «\xa0Le souffle de la révolte\xa0», un arrêt au «\xa0Bœuf sur le toit\xa0»]':'http://soufflebleu.fr/2018/02/02/attendant-souffle-de-revolte/',
'[Deux chanteuses qui arrivent et prennent leur place]':'http://soufflebleu.fr/2018/01/30/deux-chanteuses-arrivent-prennent-place/',
'[« Sons d’hiver »]':'http://soufflebleu.fr/2018/01/23/sons-dhiver/',
'[Picasso rencontre un trio de jazz]':'http://soufflebleu.fr/2017/12/31/picasso-rencontre-trio-de-jazz/',
'[Jazz, les années d’Occupation revisitées]':'http://soufflebleu.fr/2017/12/31/jazz-annees-doccupation-revisitees/',
'[Jazz musique au présent]':'http://soufflebleu.fr/2017/12/29/jazz-musique-present/',
'[Jazz, mélanges de bleus]':'http://soufflebleu.fr/2017/12/29/jazz-melanges-de-bleus/',
'[Cadeaux à faire ou à se faire.]':'http://soufflebleu.fr/2017/12/23/cadeaux-a-faire-a-se-faire-2/',
'[« Sunny » Murray, batteur.]':'http://soufflebleu.fr/2017/12/18/sunny-murray-batteur/',
'[Une froide chaleur]':'http://soufflebleu.fr/2017/12/08/une-froide-chaleur/',
'[Festival PAN, le 8 décembre 2017]':'http://soufflebleu.fr/2017/12/07/festival-pan-8-decembre-2017/',
'[Le Jazz là où ne l’attend pas]':'http://soufflebleu.fr/2017/11/28/jazz-ne-lattend/',
'[Comme une définition du Jazz]':'http://soufflebleu.fr/2017/11/28/comme-une-definition-du-jazz/',
'[UIA de Caen, JAZZ]':'http://soufflebleu.fr/2017/11/25/uia-de-caen-jazz/',
'[Illustrations du «\xa0Souffle de la révolte\xa0», avant première]':'http://soufflebleu.fr/2017/11/18/illustrations-souffle-de-revolte-premiere/',
'[Mémoire vivante.]':'http://soufflebleu.fr/2017/11/16/memoire-vivante/',
'[JAZZ, un trio]':'http://soufflebleu.fr/2017/11/16/jazz-un-trio-2/',
'[Université populaire jazz, Côte à Côte]':'http://soufflebleu.fr/2017/11/12/universite-populaire-jazz-cote-a-cote/',
'[Compléments ou prolégomènes du «\xa0souffle de la révolte\xa0» à paraître]':'http://soufflebleu.fr/2017/11/12/complements-prolegomenes-souffle-de-revolte-a-paraitre/',
'[Jazz. Retrouver Ben Webster]':'http://soufflebleu.fr/2017/11/03/jazz-retrouver-ben-webster/',
'[Jazz  ou pas ? A vous de voir. Claudia Solal et Benjamin Moussay posent la question.]':'http://soufflebleu.fr/2017/11/03/jazz-a-de-voir-claudia-solal-benjamin-moussay-posent-question/',
'[Mémoires vivantes.]':'http://soufflebleu.fr/2017/10/10/memoires-vivantes/',
'[Histoires des Etats-Unis et de France.]':'http://soufflebleu.fr/2017/10/05/histoires-etats-unis-de-france/',
'[Dreams and Daggers : Rêver l’impossible ?]':'http://soufflebleu.fr/2017/10/03/dreams-and-daggers-rever-limpossible/',
'[A propos du film «\xa0Django\xa0» de Étienne Comar]':'http://soufflebleu.fr/2017/10/03/a-propos-film-django-de-etienne-comar/',
'[Avant première du «\xa0Souffle de la révolte\xa0» à paraître en octobre 2017, pour fêter le centenaire de la révolution russe, du premier disque de jazz et l’arrivée de James Europe en France]':'http://soufflebleu.fr/2017/08/20/avant-premiere/',
'[Quelques réflexions sur la question culturelle]':'http://soufflebleu.fr/2017/07/27/quelques-reflexions-question-culturelle/',
'[Travail de plaisir et de mémoire.]':'http://soufflebleu.fr/2017/07/12/travail-de-plaisir-de-memoire/',
'[« Fats » Waller revu et actuel]':'http://soufflebleu.fr/2017/07/12/fats-waller-revu-actuel/',
'[Erroll Garner revivifié par Pierre Christophe]':'http://soufflebleu.fr/2017/07/12/erroll-garner-revivifie-pierre-christophe/',
'[30 ans après.]':'http://soufflebleu.fr/2017/07/12/30-ans-apres/',
'[Giulia Valle, musicienne de jazz]':'http://soufflebleu.fr/2017/07/11/giulia-valle-musicienne-de-jazz/',
'[George Colligan, pianiste et compositeur]':'http://soufflebleu.fr/2017/07/11/george-colligan-pianiste-compositeur/',
'[Une évocation du Paris des années 1920]':'http://soufflebleu.fr/2017/07/11/evocation-paris-annees-1920/',
'[JAZZ, Monk encore…]':'http://soufflebleu.fr/2017/07/01/jazz-monk-encore/',
'[Jazz, Michel Fernandez]':'http://soufflebleu.fr/2017/07/01/jazz-michel-fernandez/',
'[JAZZ, Du Monk et du bon]':'http://soufflebleu.fr/2017/07/01/jazz-du-monk-et-du-bon/',
'[1917-2017, Guerre et Révolution]':'http://soufflebleu.fr/2017/07/01/1917-2017-guerre-revolution/',
'[Jazz, Un continent oublié]':'http://soufflebleu.fr/2017/06/27/jazz-continent-oublie/',
'[Jazz, Les vocalistes à l’honneur sur la Côte Ouest.]':'http://soufflebleu.fr/2017/06/18/jazz-vocalistes-a-lhonneur-cote-ouest/',
'[Jazz «\xa0Supersonic\xa0» Thomas de Pourquery]':'http://soufflebleu.fr/2017/05/31/jazz-supersonic-thomas-de-pourquery/',
'[Jazz, pianiste et chanteuse Tamara Mozes]':'http://soufflebleu.fr/2017/05/31/jazz-pianiste-chanteuse-tamara-mozes/',
'[Jazz Manouche autour de la «\xa0Selmer #607\xa0»]':'http://soufflebleu.fr/2017/05/31/jazz-manouche-autour-de-selmer-607/',
'[Jazz et pas Jazz : Ripcord]':'http://soufflebleu.fr/2017/05/31/jazz-jazz-ripcord/',
'[La virtuosité humaniste d’Oscar Peterson.]':'http://soufflebleu.fr/2017/05/23/virtuosite-humaniste-doscar-peterson/',
'[Le centenaire du premier disque de jazz, 1917 une année clé dans l’histoire du monde et du jazz.]':'http://soufflebleu.fr/2017/05/21/centenaire-premier-disque-de-jazz-1917-annee-cle-lhistoire-monde-jazz/',
'[Le Jazz quand même….]':'http://soufflebleu.fr/2017/05/09/le-jazz-quand-meme/',
'[Jazz pour rigoler]':'http://soufflebleu.fr/2017/05/09/jazz-pour-rigoler/',
'[Jazz pas forcément d’hier…]':'http://soufflebleu.fr/2017/05/09/jazz-forcement-dhier/',
'[U.P Jazz du 10 mai 2017 (suite)]':'http://soufflebleu.fr/2017/05/08/u-p-jazz-10-mai-2017-suite/',
'[Musiques Noires]':'http://soufflebleu.fr/2017/05/02/musiques-noires/',
'[Jazz sous les Pommiers, 36e éditions]':'http://soufflebleu.fr/2017/05/01/jazz-pommiers-36e-editions/',
'[U. P. Jazz des 3 et 10 mai 2017]':'http://soufflebleu.fr/2017/04/27/u-p-jazz-3-10-mai-2017/',
'[Musique et chansons venues d’ailleurs]':'http://soufflebleu.fr/2017/04/11/musique-et-chansons-venues-dailleurs/',
'[Jazz un piano qui ronfle]':'http://soufflebleu.fr/2017/04/11/jazz-un-piano-qui-ronfle/',
'[Jazz, quand un saxo rencontre un autre saxo…La folie n’est pas loin…]':'http://soufflebleu.fr/2017/04/11/jazz-quand-un-saxo-rencontre-un-autre-saxo-la-folie-nest-pas-loin/',
'[Jazz quand tu nous tiens…]':'http://soufflebleu.fr/2017/04/11/jazz-quand-tu-nous-tiens/',
'[Rééditions d’une musique disparue]':'http://soufflebleu.fr/2017/03/30/reeditions-dune-musique-disparue/',
'[Sur une théorie de l’Esthétique]':'http://soufflebleu.fr/2017/03/25/sur-une-theorie-de-lesthetique/',
'[Jazz. Queens ?]':'http://soufflebleu.fr/2017/03/25/jazz-queens/',
'[Université populaire jazz le 22 mars 2017]':'http://soufflebleu.fr/2017/03/19/universite-populaire-jazz-le-22-mars-2017/',
'[Jazz, retour aux sources prénatales]':'http://soufflebleu.fr/2017/03/17/jazz-retour-aux-sources-prenatales/',
'[Jazz, Effluves du Sud]':'http://soufflebleu.fr/2017/03/17/jazz-effluves-du-sud/',
'[Sonny Rollins à propos de son album Freedom suite (1958)]':'http://soufflebleu.fr/2017/03/10/sonny-rollins-sur-freedom-suite-1958/',
'[UIA Jazz, lundi 6 mars 2017, dernière… pour cette année.]':'http://soufflebleu.fr/2017/03/05/uia-jazz-lundi-6-mars-2017-derniere-pour-cette-annee/',
'[Jazz, mémoire de batteure, Julie Saury]':'http://soufflebleu.fr/2017/02/08/jazz-memoire-de-batteure-julie-saury/',
'[JAZZ: Elvin Jones !]':'http://soufflebleu.fr/2017/01/27/jazz-elvin-jones/',
'[Jazz, Déjà la fin ? La saga Bird tire sa révérence.]':'http://soufflebleu.fr/2017/01/23/jazz-deja-la-fin-la-saga-bird-tire-sa-reverence/',
'[UIA Jazz, histoire de la batterie]':'http://soufflebleu.fr/2017/01/22/uia-jazz-histoire-de-la-batterie/',
'[Chronique jazzistique.]':'http://soufflebleu.fr/2017/01/16/chronique-jazzistique/',
'[A Nat Hentoff]':'http://soufflebleu.fr/2017/01/12/a-nat-hentoff/',
'[JAZZ, un curieux album]':'http://soufflebleu.fr/2016/12/31/jazz-un-curieux-album/',
'[JAZZ, Rattrapages : qu’il est difficile de commencer 2017 sans avoir, un peu, soldé 2016]':'http://soufflebleu.fr/2016/12/30/jazz-rattrapages-quil-est-difficile-de-commencer-2017-sans-avoir-un-peu-solde-2016/',
'[JAZZ, Rattrapages (toujours..)]':'http://soufflebleu.fr/2016/12/29/jazz-rattrapages-toujours/',
'[JAZZ, Rattrapage (encore…)]':'http://soufflebleu.fr/2016/12/29/jazz-rattrapage-encore/',
'[JAZZ, Rattrapage (suite)]':'http://soufflebleu.fr/2016/12/27/jazz-rattrapage-suite/',
'[JAZZ\t, Ménage à trois.]':'http://soufflebleu.fr/2016/12/27/jazz-menage-a-trois/',
'[JAZZ, Batteur et compositeur, Thomas Grimmonprez]':'http://soufflebleu.fr/2016/12/27/jazz-batteur-et-compositeur-thomas-grimmonprez/',
'[JAZZ de la fin d’année 2016]':'http://soufflebleu.fr/2016/12/24/jazz-de-la-fin-dannee-2016/',
'[JAZZ, Rencontres au présent]':'http://soufflebleu.fr/2016/12/23/jazz-rencontres-au-present/',
'[JAZZ ou Jass ?]':'http://soufflebleu.fr/2016/12/23/jazz-ou-jass/',
'[JAZZ, Messes basses]':'http://soufflebleu.fr/2016/12/23/jazz-messes-basses/',
'[JAZZ, Même les Hongrois…]':'http://soufflebleu.fr/2016/12/19/jazz-meme-les-hongrois/',
'[JAZZ, Portal et Vitous]':'http://soufflebleu.fr/2016/12/18/jazz-portal-et-vitous/',
'[JAZZ, Un concert intimiste du Fred Hersch trio]':'http://soufflebleu.fr/2016/12/13/jazz-un-concert-intimiste-du-fred-hersch-trio/',
'[JAZZ, Des histoires d’aujourd’hui]':'http://soufflebleu.fr/2016/12/13/jazz-des-histoires-daujourdhui/',
'[le JAZZ comme synthèse]':'http://soufflebleu.fr/2016/11/20/le-jazz-comme-synthese/',
'[JAZZ, un art du duo]':'http://soufflebleu.fr/2016/11/20/jazz-un-art-du-duo/',
'[JAZZ et musiques de la Syrie]':'http://soufflebleu.fr/2016/11/20/jazz-et-musiques-de-la-syrie/',
'[JAZZ et la musique de Berlin]':'http://soufflebleu.fr/2016/11/20/jazz-et-la-musique-de-berlin/',
'[JAZZ et jazz]':'http://soufflebleu.fr/2016/11/20/jazz-et-jazz/',
'[JAZZ en fonds sous marins bretons]':'http://soufflebleu.fr/2016/11/20/jazz-en-fonds-sous-marins-bretons/',
'[Jazz accompagné]':'http://soufflebleu.fr/2016/11/20/jazz-accompagne/',
'[JAZZ]':'http://soufflebleu.fr/2016/11/20/jazz-3/',
'[A propos de la «\xa0Beat Generation\xa0»]':'http://soufflebleu.fr/2016/10/03/a-propos-de-la-beat-generation/',
'[Pontoise le 27 septembre 2016]':'http://soufflebleu.fr/2016/09/25/pontoise-le-27-septembre-2016/',
'[Pour Pontoise le 20 septembre 2016]':'http://soufflebleu.fr/2016/09/19/pour-pontoise-le-20-septembre-2016/',
'[Jazz et musiques contemporaines]':'http://soufflebleu.fr/2016/09/08/jazz-et-musiques-contemporaines/',
'[Jazz]':'http://soufflebleu.fr/2016/09/08/jazz-2/',
'[Rencontres de cultures]':'http://soufflebleu.fr/2016/09/06/rencontres-de-cultures/',
'[Étrange rencontre]':'http://soufflebleu.fr/2016/09/06/etrange-rencontre/',
'[Musiques de nos mémoires.]':'http://soufflebleu.fr/2016/08/26/musiques-de-nos-memoires/',
'[Jazz. Le palmarès de la revue Jazzthing]':'http://soufflebleu.fr/2016/08/16/jazz-le-palmares-de-la-revue-jazzthing/',
'[Jazz. Mondial ? Non, Cosmique !]':'http://soufflebleu.fr/2016/08/12/jazz-mondial-non-cosmique/',
'[Jazz. Le jazz et l’Europe]':'http://soufflebleu.fr/2016/08/12/jazz-le-jazz-et-leurope/',
'[Jazz, De la guitare, France/États-Unis]':'http://soufflebleu.fr/2016/08/12/jazz-de-la-guitare-franceetats-unis/',
'[Jazz d’ailleurs et de toujours]':'http://soufflebleu.fr/2016/08/12/jazz-dailleurs-et-de-toujours/',
'[JAZZ, Ballades]':'http://soufflebleu.fr/2016/08/12/jazz-ballades/',
'[Jazz. A trois, c’est parti…]':'http://soufflebleu.fr/2016/08/12/jazz-a-trois-cest-parti/',
'[Crest 2016, les villes du jazz, Philadelphie et Pittsburgh]':'http://soufflebleu.fr/2016/07/31/crest-2016-les-villes-du-jazz-philadelphie-et-pittsburgh/',
'[Jazz, La machine à remonter le temps (3)]':'http://soufflebleu.fr/2016/07/16/jazz-la-machine-a-remonter-le-temps-3/',
'[Jazz, La machine à remonter le temps (2)]':'http://soufflebleu.fr/2016/07/16/jazz-la-machine-a-remonter-le-temps-2/',
'[Jazz, La machine à remonter le temps. (1)]':'http://soufflebleu.fr/2016/07/16/jazz-la-machine-a-remonter-le-temps-1/',
'[Le champ jazzistique vu à travers les festivals de l’été.]':'http://soufflebleu.fr/2016/07/10/le-champ-jazzistique-vu-a-travers-les-festivals-de-lete/',
'[JAZZ, il faut aussi le lire…]':'http://soufflebleu.fr/2016/07/10/jazz-il-faut-aussi-le-lire/',
'[JAZZ, le 37e festival Django Reinhardt.]':'http://soufflebleu.fr/2016/06/13/jazz-le-37e-festival-django-reinhardt/',
'[Jazz. Revoir New York ?]':'http://soufflebleu.fr/2016/06/04/jazz-revoir-new-york/',
'[Le jazz comme vecteur de la fraternité]':'http://soufflebleu.fr/2016/05/30/le-jazz-comme-vecteur-de-la-fraternite/',
'[JAZZ, perdre pour retrouver, à propos du Dave Brubeck quartet]':'http://soufflebleu.fr/2016/05/23/jazz-perdre-pour-retrouver-a-propos-du-dave-brubeck-quartet/',
'[JAZZ, Louis Moreau Gottschalk, ancêtre du jazz ?]':'http://soufflebleu.fr/2016/05/23/jazz-louis-moreau-gottschalk-ancetre-du-jazz/',
'[Rendez-vous à Coutances]':'http://soufflebleu.fr/2016/05/03/rendez-vous-a-coutances/',
'[JAZZ. Musique de la mémoire]':'http://soufflebleu.fr/2016/04/10/jazz-musique-de-la-memoire/',
'[Un festival de jazz, des …]':'http://soufflebleu.fr/2016/04/03/un-festival-de-jazz-des/',
'[Des nouvelles du jazz en Allemagne]':'http://soufflebleu.fr/2016/04/03/des-nouvelles-du-jazz-en-allemagne/',
'[Jazz. Un absent des dictionnaires très présent]':'http://soufflebleu.fr/2016/03/26/jazz-un-absent-des-dictionnaires-tres-present/',
'[Jazz. Chercher sa voi(e)x]':'http://soufflebleu.fr/2016/03/26/jazz-chercher-sa-voiex/',
'[Jazz. Quand les Cors sonnent…]':'http://soufflebleu.fr/2016/03/23/jazz-quand-les-cors-sonnent/',
'[Jazz. En direct du Brésil]':'http://soufflebleu.fr/2016/03/23/jazz-en-direct-du-bresil/',
'[Le Jazz comme eau de jouvence.]':'http://soufflebleu.fr/2016/03/22/le-jazz-comme-eau-de-jouvence/',
'[Jazz. Pour tous les opprimés qui dansent au ciel et ailleurs]':'http://soufflebleu.fr/2016/03/22/jazz-pour-tous-les-opprimes-qui-dansent-au-ciel-et-ailleurs/',
'[Jazz, Paris, 1958 et 1960. De la peur à la peur et la joie du jazz.]':'http://soufflebleu.fr/2016/03/03/jazz-paris-1958-et-1960-de-la-peur-a-la-peur-et-la-joie-du-jazz/',
'[Jazz, A propos d’une rétrospective Don Byas]':'http://soufflebleu.fr/2016/03/01/jazz-a-propos-dune-retrospective-don-byas/',
'[Nouveautés Jazz]':'http://soufflebleu.fr/2016/02/23/nouveautes-jazz-9/',
'[Jazz, Louis Armstrong, 1962]':'http://soufflebleu.fr/2016/02/23/jazz-louis-armstrong-1962/',
'[Jazz, Volume 2 de la collection Quintessence consacrée à Sonny Rollins pour les années 1957-1962]':'http://soufflebleu.fr/2016/02/20/jazz-volume-2-de-la-collection-quintessence-consacree-a-sonny-rollins-pour-les-annees-1957-1962/',
'[JAZZ, Les aventures de l’Oiseau se poursuivent]':'http://soufflebleu.fr/2016/02/20/jazz-les-aventures-de-loiseau-se-poursuivent/',
'[Jazz, Un retour]':'http://soufflebleu.fr/2016/01/24/jazz-un-retour/',
'[Jazz, Noir c’est Noir, un message de Ran Blake pianiste, compositeur et octogénaire.]':'http://soufflebleu.fr/2016/01/24/jazz-noir-cest-noir-un-message-de-ran-blake-pianiste-compositeur-et-octogenaire/',
'[Jazz, Michel Fernandez saxophoniste]':'http://soufflebleu.fr/2016/01/24/jazz-michel-fernandez-saxophoniste/',
'[Jazz. Une nouvelle école ?]':'http://soufflebleu.fr/2016/01/02/jazz-une-nouvelle-ecole/',
'[Jazz. Daroux/Sardaby même combat ?]':'http://soufflebleu.fr/2016/01/02/jazz-darouxsardaby-meme-combat/',
'[Jazz. Compositeure, vous avez dit compositeure ?]':'http://soufflebleu.fr/2016/01/02/jazz-compositeure-vous-avez-dit-compositeure/',
'[Jazz. Musique de notre temps ?]':'http://soufflebleu.fr/2016/01/02/3305/',
'[Jazz. Musique de nos temps]':'http://soufflebleu.fr/2015/12/29/jazz-musique-de-nos-villes/',
'[Jazz. Gérard Marais quartet tout simplement.]':'http://soufflebleu.fr/2015/12/29/jazz-gerard-marais-quartet-tout-simplement/',
'[Jazz. Construire un son]':'http://soufflebleu.fr/2015/12/29/jazz-construire-un-son/',
'[Jazz. Un souffle de fraternité]':'http://soufflebleu.fr/2015/12/28/jazz-un-souffle-de-fraternite/',
'[Jazz. Rien de moins qu’un big band pour René…]':'http://soufflebleu.fr/2015/12/28/jazz-rien-de-moins-quun-big-band-pour-rene/',
'[Jazz. Quand un piano rencontre une batterie…]':'http://soufflebleu.fr/2015/12/28/jazz-quand-un-piano-rencontre-une-batterie/',
'[JAZZ, A nos disparus]':'http://soufflebleu.fr/2015/12/28/jazz-a-nos-disparus/',
'[Jazz, de quelques oublis et nouveautés]':'http://soufflebleu.fr/2015/12/21/jazz-de-quelques-oublis-et-nouveautes/',
'[JAZZ, De quelques parutions récentes (1)]':'http://soufflebleu.fr/2015/12/20/jazz-de-quelques-parutions-recentes-1/',
'[Le temps de lire, la sélection livres de Nicolas BENIES]':'http://soufflebleu.fr/2015/12/08/le-temps-de-lire-la-selection-livres-de-nicolas-benies/',
'[Le temps d’écouter, la sélection de CD de jazz de Nicolas Béniès]':'http://soufflebleu.fr/2015/12/08/3230/',
'[La Bourgogne, terre d’accueil du jazz]':'http://soufflebleu.fr/2015/12/05/la-bourgogne-terre-daccueil-du-jazz/',
'[Enfance(s) du jazz ? Enfants du jazz ?]':'http://soufflebleu.fr/2015/12/05/enfances-du-jazz-enfants-du-jazz/',
'[Appréhender le jazz ? Est-ce possible ?]':'http://soufflebleu.fr/2015/12/05/apprehender-le-jazz-est-ce-possible/',
'[JAZZ, une nouvelle chanteuse]':'http://soufflebleu.fr/2015/11/23/jazz-une-nouvelle-chanteuse/',
'[JAZZ, sans un mot, un jazz Babel ?]':'http://soufflebleu.fr/2015/11/23/jazz-sans-un-mot-un-jazz-babel/',
'[JAZZ ( ?), de l’inattendu]':'http://soufflebleu.fr/2015/11/23/jazz-de-linattendu/',
'[Jazz, nouveautés]':'http://soufflebleu.fr/2015/11/13/jazz-nouveautes/',
'[Un batteur et deux fils de… au théâtre de Caen.]':'http://soufflebleu.fr/2015/11/06/un-batteur-et-deux-fils-de-au-theatre-de-caen/',
'[Jazz, Le volume 10 de la fausse-vraie intégrale de Charlie Parker]':'http://soufflebleu.fr/2015/10/25/jazz-le-volume-10-de-la-fausse-vraie-integrale-de-charlie-parker/',
'[JAZZ  Deux chanteuses françaises contemporaines]':'http://soufflebleu.fr/2015/10/25/jazz-deux-chanteuses-francaises-contemporaines/',
'[Histoire à écrire.]':'http://soufflebleu.fr/2015/10/08/histoire-a-ecrire/',
'[BLUES.]':'http://soufflebleu.fr/2015/10/08/blues/',
'[JAZZ, Sylvain Beuf]':'http://soufflebleu.fr/2015/10/07/jazz-sylvain-beuf/',
'[JAZZ, Jean Loup Longnon]':'http://soufflebleu.fr/2015/10/07/jazz-jean-loup-longnon/',
'[JAZZ, Antonio Sanchez]':'http://soufflebleu.fr/2015/10/07/jazz-antonio-sanchez/',
'[JAZZ, un, deux… festivals de jazz et d’autre]':'http://soufflebleu.fr/2015/10/05/jazz-un-deux-festivals-de-jazz-et-dautre/',
'[Minifest 10e (2)]':'http://soufflebleu.fr/2015/10/04/minifest-10e-2/',
'[Un visiteur au regard neuf du Minifest, Jean-François Viaud]':'http://soufflebleu.fr/2015/10/01/un-visiteur-au-regard-neuf-du-minifest-jean-francois-viaud/',
'[Le minifest fête ses 10 ans]':'http://soufflebleu.fr/2015/09/29/le-minifest-fete-ses-10-ans/',
'[Ray Anderson, tromboniste]':'http://soufflebleu.fr/2015/09/06/ray-anderson-tromboniste/',
'[Cécile McLorin Salvant, deuxième]':'http://soufflebleu.fr/2015/09/06/cecile-mclorin-salvant-deuxieme/',
'[Hommage]':'http://soufflebleu.fr/2015/09/05/hommage/',
'[Un nouvel imaginaire étasunien ?]':'http://soufflebleu.fr/2015/08/27/un-nouvel-imaginaire-etasunien/',
'[Miriam Makeba, chanteuse actuelle]':'http://soufflebleu.fr/2015/08/19/miriam-makeba-chanteuse-actuelle/',
'[Mentionner la musique du film]':'http://soufflebleu.fr/2015/08/19/mentionner-la-musique-du-film/',
'[Rendez-vous à Crest du mardi 4 août au samedi 8 août 2015]':'http://soufflebleu.fr/2015/07/31/rendez-vous-a-crest-du-mardi-4-aout-au-samedi-8-aout-2015/',
'[Quelques pochettes des années 1950 aux États-Unis]':'http://soufflebleu.fr/2015/07/19/quelques-pochettes-des-annees-1950-aux-etats-unis/',
'[Un compositeur audacieux et timide]':'http://soufflebleu.fr/2015/07/08/un-compositeur-audacieux-et-timide/',
'[Un ami est parti]':'http://soufflebleu.fr/2015/07/05/un-ami-est-parti/',
'[Jazz en livre, fille recherche père disparu]':'http://soufflebleu.fr/2015/06/29/jazz-en-livre-fille-recherche-pere-disparu/',
'[Un révolutionnaire tranquille]':'http://soufflebleu.fr/2015/06/25/un-revolutionnaire-tranquille/',
'[Quand le jazz est là… la bossa s’en va…]':'http://soufflebleu.fr/2015/06/01/quand-le-jazz-est-la-la-bossa-sen-va/',
'[A propos de Michel Warlop, concerts de Jean Toupance à Granville.]':'http://soufflebleu.fr/2015/05/31/a-propos-de-michel-warlop-concerts-de-jean-toupance-a-granville/',
'[Jazz, Charlie Parker en direct]':'http://soufflebleu.fr/2015/05/31/2792/',
'[Live in Paris, 1960]':'http://soufflebleu.fr/2015/05/24/live-in-paris-1960/',
'[Retour de Jazz Sous les Pommiers (Coutances, mai 2015)]':'http://soufflebleu.fr/2015/05/18/retour-de-jazz-sous-les-pommiers-coutances-mai-2015/',
'[JAZZ Trombone (allemand)]':'http://soufflebleu.fr/2015/05/05/jazz-trombone-allemand/',
'[JAZZ, Diego Imbert]':'http://soufflebleu.fr/2015/05/05/jazz-diego-imbert/',
'[Jazz, Charles Lloyd]':'http://soufflebleu.fr/2015/05/05/jazz-charles-lloyd/',
'[JAZZ, le troisième type ?]':'http://soufflebleu.fr/2015/05/04/jazz-le-troisieme-type/',
'[Jazz, Stan Getz, musicien élégant]':'http://soufflebleu.fr/2015/04/26/jazz-stan-getz-musicien-elegant/',
'[Université populaire Jazz, mercredi 29 avril 2015, 18h – 19h 30 Café Mancel]':'http://soufflebleu.fr/2015/04/25/universite-populaire-jazz-mercredi-29-avril-2015-18h-19h-30-cafe-mancel/',
'[Jazz, Une étrange structure]':'http://soufflebleu.fr/2015/04/20/jazz-une-etrange-structure/',
'[Nouveautés jazz, à ne pas manquer]':'http://soufflebleu.fr/2015/04/18/nouveautes-jazz-a-ne-pas-manquer/',
'[Nouveautés Jazz]':'http://soufflebleu.fr/2015/04/18/nouveautes-jazz-8/',
'[Nouveautés Jazz]':'http://soufflebleu.fr/2015/04/18/nouveautes-jazz-3/',
'[Jazz et chansons]':'http://soufflebleu.fr/2015/04/18/jazz-et-chansons/',
'[Jazz. Découverte.]':'http://soufflebleu.fr/2015/04/18/jazz-decouverte/',
'[Des nouvelles du petit label]':'http://soufflebleu.fr/2015/04/18/des-nouvelles-du-petit-label/',
'[Une anthologie nécessaire. Pour Barney.]':'http://soufflebleu.fr/2015/04/08/une-anthologie-necessaire-pour-barney/',
'[Une fusion étrange, venue d’ailleurs. Le jazz et la France]':'http://soufflebleu.fr/2015/04/07/une-fusion-etrange/',
'[Deux festivals de jazz]':'http://soufflebleu.fr/2015/04/07/deux-festivals-de-jazz/',
'[Billie Holiday est née le 7 avril 1915. 100 ans après, le génie est toujours là.]':'http://soufflebleu.fr/2015/04/07/billie-holiday-est-nee-le-7-avril-1915-100-ans-apres-le-genie-est-toujours-la/',
'[Jazz et piano en quatuor (2)]':'http://soufflebleu.fr/2015/03/30/jazz-et-piano-en-quatuor-2/',
'[Jazz et piano]':'http://soufflebleu.fr/2015/03/30/jazz-et-piano/',
'[Jazz en Big Band]':'http://soufflebleu.fr/2015/03/30/jazz-en-big-band/',
'[Jazz, des standards dans les nouveautés]':'http://soufflebleu.fr/2015/03/30/jazz-des-standards-dans-les-nouveautes/',
'[Deux rendez-vous pour le jazz]':'http://soufflebleu.fr/2015/03/26/deux-rendez-vous-pour-le-jazz/',
'[Miles, notre contemporain… pour l’éternité !]':'http://soufflebleu.fr/2015/03/03/miles-notre-contemporain-pour-leternite/',
'[JAZZ, Un Modern Jazz Quartet du 21e siècle ?]':'http://soufflebleu.fr/2015/02/28/jazz-un-modern-jazz-quartet-du-21e-siecle/',
'[JAZZ,  La popularité du jazz en Allemagne]':'http://soufflebleu.fr/2015/02/28/jazz-la-popularite-du-jazz-en-allemagne/',
'[Relecture des années 1970.]':'http://soufflebleu.fr/2015/02/24/relecture-des-annees-1970/',
'[Louis Armstrong en France, 1948]':'http://soufflebleu.fr/2015/02/22/louis-armstrong-en-france-1948/',
'[JAZZ : les nouveautés du côté des pianistes]':'http://soufflebleu.fr/2015/02/15/jazz-les-nouveautes-du-cote-des-pianistes/',
'[Le réseau FOCUS JAZZ présente : 1 MOIS DE JAZZ EN BASSE-NORMANDIE MARS 2015]':'http://soufflebleu.fr/2015/02/04/le-reseau-focus-jazz-presente-1-mois-de-jazz-en-basse-normandie-mars-2015/',
'[U.P Jazz du mercredi 28 janvier 2015]':'http://soufflebleu.fr/2015/01/24/u-p-jazz-du-mercredi-28-janvier-2015/',
'[Nouveautés jazz du dernier trimestre 2014]':'http://soufflebleu.fr/2015/01/13/nouveautes-jazz-du-dernier-trimestre-2014/',
'[Partir… Loin…]':'http://soufflebleu.fr/2015/01/03/partir-loin/',
'[Fête aux Antilles et à Paris]':'http://soufflebleu.fr/2015/01/03/fete-aux-antilles-et-a-paris/',
'[Séminaire jazz, UP Caen.]':'http://soufflebleu.fr/2015/01/02/seminaire-jazz-up-caen/',
'[Merengue !]':'http://soufflebleu.fr/2014/12/28/merengue/',
'[JAZZ,  le cas Martial Solal.]':'http://soufflebleu.fr/2014/12/23/jazz-le-cas-martial-solal/',
'[JAZZ, Coups de cœur]':'http://soufflebleu.fr/2014/12/18/jazz-coups-de-coeur/',
'[1+1+1=3=1]':'http://soufflebleu.fr/2014/12/12/11131/',
'[JAZZ, Un trio classique ?]':'http://soufflebleu.fr/2014/12/07/un-trio-classique/',
'[JAZZ, Faire frucifier l’héritage]':'http://soufflebleu.fr/2014/12/07/jazz-faire-frucifier-lheritage/',
'[Un batteur percussionniste Manu Katché]':'http://soufflebleu.fr/2014/11/28/un-batteur-percussionniste-manu-katche/',
'[Trois par trois]':'http://soufflebleu.fr/2014/11/28/trois-par-trois/',
'[Les pas de Coltrane]':'http://soufflebleu.fr/2014/11/28/les-pas-de-coltrane/',
'[Jazz ou pas Jazz ? Qu’est-ce que le jazz ?]':'http://soufflebleu.fr/2014/11/28/jazz-ou-pas-jazz-quest-ce-que-le-jazz/',
'[Jazz et autres cultures]':'http://soufflebleu.fr/2014/11/28/jazz-et-autres-cultures/',
'[Il faut danser…]':'http://soufflebleu.fr/2014/11/28/il-faut-danser/',
'[Du tango à la poésie]':'http://soufflebleu.fr/2014/11/28/du-tango-a-la-poesie/',
'[Un quartet de jazz à écouter]':'http://soufflebleu.fr/2014/11/27/un-quartet-de-jazz-a-ecouter/',
'[JAZZ et Afrobeat]':'http://soufflebleu.fr/2014/11/27/jazz-et-afrobeat/',
'[Proust en musique]':'http://soufflebleu.fr/2014/11/25/proust-en-musique/',
'[JAZZ. A deux, c’est mieux ?]':'http://soufflebleu.fr/2014/11/23/jazz-a-deux-cest-mieux/',
'[Séminaire jazz du mercredi 26 novembre 2014]':'http://soufflebleu.fr/2014/11/22/seminaire-jazz-du-mercredi-26-novembre-2014/',
'[Paris, capitale du jazz.]':'http://soufflebleu.fr/2014/10/31/paris-capitale-du-jazz/',
'[Vibrer avec Doriz]':'http://soufflebleu.fr/2014/10/27/vibrer-avec-doriz/',
'[Du jazz de toujours…]':'http://soufflebleu.fr/2014/10/27/du-jazz-de-toujours/',
'[Pour le mélange passé/présent]':'http://soufflebleu.fr/2014/10/24/pour-le-melange-passepresent/',
'[Hommes et problèmes du jazz]':'http://soufflebleu.fr/2014/10/19/hommes-et-problemes-du-jazz/',
'[A l’automne, les festivals de jazz se ramassent à la pelle… (2)]':'http://soufflebleu.fr/2014/10/19/a-lautomne-les-festivals-de-jazz-se-ramassent-a-la-pelle-2/',
'[A l’automne, les festivals de jazz se ramassent à la pelle… (1)]':'http://soufflebleu.fr/2014/10/19/a-lautomne-les-festivals-de-jazz-se-ramassent-a-la-pelle-1/',
'[Saga birdienne]':'http://soufflebleu.fr/2014/10/16/saga-birdienne/',
'[Quinzième festival villes des musiques du monde.]':'http://soufflebleu.fr/2014/10/01/quinzieme-festival-villes-des-musiques-du-monde/',
'[La perfection… presque]':'http://soufflebleu.fr/2014/09/09/la-perfection-presque/',
'[Faut rigoler….]':'http://soufflebleu.fr/2014/09/09/faut-rigoler/',
'[Mai juin 1962 à Paris…]':'http://soufflebleu.fr/2014/09/08/mai-juin-1962-a-paris/',
'[Jazz ou pas jazz ?]':'http://soufflebleu.fr/2014/07/29/jazz-ou-pas-jazz/',
'[JAZZ, nouveautés en retard]':'http://soufflebleu.fr/2014/07/27/jazz-nouveautes-en-retard/',
'[Des nouveautés en jazz de cette année]':'http://soufflebleu.fr/2014/07/27/des-nouveautes-en-jazz-de-cette-annee/',
'[A propos d’une réédition en vinyle de «\xa0Cookbook\xa0» vol 1 de Eddie Lockjaw Davis]':'http://soufflebleu.fr/2014/07/15/a-propos-dune-reedition-en-vinyle-de-cookbook-vol-1-de-eddie-lockjaw-davis/',
'[Charlie Haden nous a quittés…]':'http://soufflebleu.fr/2014/07/14/charlie-haden-nous-a-quittes/',
'[Le côté du piano jazz.]':'http://soufflebleu.fr/2014/07/07/le-cote-du-piano-jazz/',
'[JAZZ & CINEMA]':'http://soufflebleu.fr/2014/07/06/jazz-cinema/',
'[Louis Armstrong volume 13 de l’Intégrale]':'http://soufflebleu.fr/2014/07/04/louis-armstrong-volume-13-de-lintegrale/',
'[Dédicace du «\xa0Souffle de la liberté\xa0» au Brouillon de culture le 28 juin 2014]':'http://soufflebleu.fr/2014/06/24/1946/',
'[Autour des festivals.]':'http://soufflebleu.fr/2014/06/13/autour-des-festivals/',
'[Une sélection de nouveautés en jazz]':'http://soufflebleu.fr/2014/06/09/une-selection-de-nouveautes-en-jazz/',
'[Compte rendu de la 33e édition de JSP]':'http://soufflebleu.fr/2014/06/05/compte-rendu-de-la-33e-edition-de-jsp/',
'[Une exposition multimédia à la Cité de la Musique]':'http://soufflebleu.fr/2014/06/04/une-exposition-multimedia-a-la-cite-de-la-musique/',
'[Les femmes du JAZZ, Mary-Lou Williams]':'http://soufflebleu.fr/2014/06/03/les-femmes-du-jazz/',
'[JAZZ Cool en Europe]':'http://soufflebleu.fr/2014/06/02/jazz-cool-en-europe/',
'[John Coltrane, pour toujours]':'http://soufflebleu.fr/2014/05/28/john-coltrane-pour-toujours/',
'[Europa djazz et jazz sous les pommiers, deux grands festivals de jazz]':'http://soufflebleu.fr/2014/05/07/europa-djazz-et-jazz-sous-les-pommiers-deux-grands-festivals-d-ejazz/',
'[Présentation du festival Jazz Sous les Pommiers]':'http://soufflebleu.fr/2014/05/04/presentation-du-festival-jazz-sous-les-pommiers/',
'[Annonce de mon prochain livre, «\xa0Le souffle de la liberté\xa0»]':'http://soufflebleu.fr/2014/05/04/annonce-de-mon-prochain-livre-le-souffle-de-la-liberte/',
'[JAZZ, suite des aventures du Bird]':'http://soufflebleu.fr/2014/04/21/jazz-suite-des-aventures-du-bird/',
'[Présentation du festival de jazz de Coutances mai 2014]':'http://soufflebleu.fr/2014/04/19/presentation-du-festival-de-jazz-de-coutances-mai-2014/',
'[A travers les nouveautés du JAZZ (4)]':'http://soufflebleu.fr/2014/04/17/a-travers-les-nouveutes-du-jazz-4/',
'[Autour de quelques nouveautés en JAZZ (1)]':'http://soufflebleu.fr/2014/04/15/autour-de-quelques-nouveautes-en-jazz-1/',
'[A travers les nouveautés JAZZ (2)]':'http://soufflebleu.fr/2014/04/15/a-travers-les-nouveautes-jazz-2/',
'[Un travail de mémoire.]':'http://soufflebleu.fr/2014/04/12/un-travail-de-memoire/',
'[Jazz, Billy Hart Quartet]':'http://soufflebleu.fr/2014/04/02/jazz-billy-hart-quartet/',
'[Une époque et un label, «\xa0Swing\xa0»]':'http://soufflebleu.fr/2014/03/23/une-epoque-et-un-label-swing/',
'[DVD La leçon de jazz]':'http://soufflebleu.fr/2014/03/03/dvd-la-lecon-de-jazz/',
'[Un hommage au présent]':'http://soufflebleu.fr/2014/02/16/un-hommage-au-present/',
'[Le jazz Outre Rhin]':'http://soufflebleu.fr/2014/02/16/le-jazz-outre-rhin/',
'[L’art du trio jazz]':'http://soufflebleu.fr/2014/02/16/lart-du-trio-jazz/',
'[La Norvège chez ECM]':'http://soufflebleu.fr/2014/02/16/la-norvege-chez-ecm/',
'[Du jazz et du swing…]':'http://soufflebleu.fr/2014/02/16/du-jazz-et-du-swing/',
'[Rendez-vous de la semaine du 18 au 22 février 2014]':'http://soufflebleu.fr/2014/02/13/rendez-vous-de-la-semaine-du-18-au-22-fevrier-2014/',
'[Autour du 70e anniversaire du débarquement, côté jazz.]':'http://soufflebleu.fr/2014/01/31/1591/',
'[Rendez-vous de la semaine 28 janvier et 1er février 2014]':'http://soufflebleu.fr/2014/01/27/rendez-vous-de-la-semaine-28-janvier-et-1er-fevrier-2014/',
'[Allez aux concerts]':'http://soufflebleu.fr/2014/01/20/allez-aux-concerts/',
'[UP Jazz]':'http://soufflebleu.fr/2014/01/19/up-jazz/',
'[Le jazz débarque en France. Naissance d’histoires d’amour…]':'http://soufflebleu.fr/2014/01/12/le-jazz-debarque-en-france-naissance-dhistoires-damour/',
'[Jazz vivant, le temps des festivals… de la côte.]':'http://soufflebleu.fr/2014/01/12/jazz-vivant-le-temps-des-festivals-de-la-cote/',
'[A propos de l’AACM, de Chicago et d’un label, RogueArt.]':'http://soufflebleu.fr/2014/01/03/a-propos-de-laacm-de-chicago-et-dun-label-rogueart/',
'[Visions fugitives du jazz]':'http://soufflebleu.fr/2013/12/31/visions-fugitives-du-jazz/',
'[Jazz ?]':'http://soufflebleu.fr/2013/12/31/jazz/',
'[Nouveautés jazz, du côté de la guitare.]':'http://soufflebleu.fr/2013/12/30/nouveautes-jazz-du-cote-de-la-guitare/',
'[En passant par Chicago… Université populaire sur le jazz 2012 – 2013]':'http://soufflebleu.fr/2013/12/28/en-passant-par-chicago-universite-populaire-sur-le-jazz-2012-2013/',
'[Nouveautés jazz (7)]':'http://soufflebleu.fr/2013/12/27/nouveautes-jazz-7/',
'[Nouveautés Jazz (6)]':'http://soufflebleu.fr/2013/12/24/nouveautes-jazz-6/',
'[Nouveautés Jazz (5)]':'http://soufflebleu.fr/2013/12/24/nouveautes-jazz-5/',
'[Nouveautés Jazz (4), Issa rencontre Char ?]':'http://soufflebleu.fr/2013/12/24/nouveautes-jazz-4/',
'[Nouveautés Jazz, à propos de guitare]':'http://soufflebleu.fr/2013/12/23/nouveautes-jazz-a-propos-de-guitare/',
'[Tout autour du piano (2)]':'http://soufflebleu.fr/2013/12/22/tout-autour-du-piano-2/',
'[Nouveautés Jazz (2)  Tout autour du piano]':'http://soufflebleu.fr/2013/12/22/nouveautes-jazz-2-tout-autour-du-piano/',
'[Nouveautés Jazz.]':'http://soufflebleu.fr/2013/12/22/nouveautes-jazz/',
'[Rendez-vous exceptionnel ce dimanche à 10h30]':'http://soufflebleu.fr/2013/12/21/rendez-vous-exceptionnel-ce-dimanche-a-10h30/',
'[Le renouveau des brass bands]':'http://soufflebleu.fr/2013/12/01/le-renouveau-des-brass-bands/',
'[Redécouverte.]':'http://soufflebleu.fr/2013/11/30/redecouverte-2/',
'[Rendez-vous le samedi 30 novembre 2013 au Café Mancel pour un voyage dans les nouveautés jazz, à 17 h]':'http://soufflebleu.fr/2013/11/24/rendez-vous-le-samedi-30-novembre-2013-au-cafe-mancel-pour-un-voyage-dans-les-nouveautes-jazz-a-17-h/',
'[Rendez-vous le 27 novembre 2013 de 18h à 19h30 au Café Mancel pour le séminaire de jazz]':'http://soufflebleu.fr/2013/11/24/rendez-vous-le-27-novembre-2013-de-18h-a-19h30-au-cafe-mancel-pour-le-seminaire-de-jazz/',
'[Les découvertes sont rares…]':'http://soufflebleu.fr/2013/10/06/1215/',
'[Marjolaine Reymond en Aphrodite ?]':'http://soufflebleu.fr/2013/10/05/marjolaine-reymond-en-aphrodite/',
'[Un mariage pour tous]':'http://soufflebleu.fr/2013/10/05/article-publie-dans-lus-mad-de-septembre-2013/',
'[Nouveautés en jazz, octobre 2013]':'http://soufflebleu.fr/2013/10/02/nouveautes-en-jazz-octobre-2013/',
'[Hommage à Marian McPartland, interview dans DownBeat de 1957]':'http://soufflebleu.fr/2013/09/04/hommage-a-marian-mcpartland-interview-dans-downbeat-de-1957/',
'[Aspects de la guitare contemporaine, en jazz (?)]':'http://soufflebleu.fr/2013/08/21/aspects-de-la-guitare-contemporaine-en-jazz/',
'[Histoire culturelle des Etats-Unis, une leçon de dialectique]':'http://soufflebleu.fr/2013/08/19/histoire-culturelle-des-etats-unis-une-lecon-de-dialectique/',
'[A propos d’une histoire culturelle des Etats-Unis]':'http://soufflebleu.fr/2013/08/19/a-propos-dune-histoire-culturelle-des-etats-unis/',
'[Un batteur d’entre les batteurs : Roy Haynes]':'http://soufflebleu.fr/2013/08/17/un-batteur-dentre-les-batteurs-roy-haynes/',
'[La saga Bird, saga du 20e siècle.]':'http://soufflebleu.fr/2013/08/16/la-saga-bird-saga-du-20e-siecle/',
'[Culture, vous avez dit crédit ?]':'http://soufflebleu.fr/2013/07/10/article-publie-dans-le-n-42-de-la-revue-de-lecole-emancipee-juillet-2013/',
'[Un festival… des festivals… de jazz]':'http://soufflebleu.fr/2013/07/10/article-publie-dans-la-revue-de-lecole-emancipee-n-42/',
'[Jazz, un trio]':'http://soufflebleu.fr/2013/07/08/jazz-un-trio/',
'[Le jazz en 1954 – 1961]':'http://soufflebleu.fr/2013/06/21/le-jazz-en-1954-1961/',
'[Nouveautés en jazz, juin 2013]':'http://soufflebleu.fr/2013/06/02/nouveautes-en-jazz-juin-2013/',
'[Rendez-vous le 6 juin 2013, au Café mancel, le jazz débarque]':'http://soufflebleu.fr/2013/06/01/rendez-vous-le-6-juin-2013-au-cafe-mancel-le-jazz-debarque/',
'[Autour de quelques nouveautés en jazz]':'http://soufflebleu.fr/2013/05/20/autour-de-quelques-nouveautes-en-jazz/',
'[Un rendez-vous raté]':'http://soufflebleu.fr/2013/05/19/un-rendez-vous-rate/',
'[Impressions de Jazz Sous les Pommiers, 4 – 11 mai 2013, 32e édition.]':'http://soufflebleu.fr/2013/05/19/impressions-de-jazz-sous-les-pommiers-4-11-mai-2013-32e-edition/',
'[Un rendez-vous exceptionnel, le 6 juin 2013, café mancel]':'http://soufflebleu.fr/2013/05/12/un-rendez-vous-exceptionnel/',
'[Pour Max Roach]':'http://soufflebleu.fr/2013/05/02/pour-max-roach/',
'[Intégrale Louis Armstrong, volume 12]':'http://soufflebleu.fr/2013/05/02/integrale-louis-armstrong-volume-12/',
'[Une présentation de Jazz sous les Pommiers 2013]':'http://soufflebleu.fr/2013/04/24/une-presentation-de-jazz-sous-les-pommiers-2013/',
'[Un art spécifique, celui de la rencontre, du couple]':'http://soufflebleu.fr/2013/04/14/artcle-publie-dans-la-revue-de-lecole-emancipee-davril-2013-2/',
'[Les festivals de jazz de mai 2013]':'http://soufflebleu.fr/2013/04/10/les-festivals-de-jazz-de-mai-2013/',
'[Nouveautés jazz, les saxophonistes]':'http://soufflebleu.fr/2013/03/31/nouveautes-jazz-les-saxophonistes/',
'[Nouveautés en jazz, les pianistes]':'http://soufflebleu.fr/2013/03/31/nouveautes-en-jazz-les-pianistes/',
'[Nouveautés jazz (2)]':'http://soufflebleu.fr/2013/03/25/nouveautes-jazz-2/',
'[Dans les nouveautés en jazz]':'http://soufflebleu.fr/2013/03/25/dans-les-nouveautes-en-jaz/',
'[Université populaire jazz, mercredi 13 mars 2013, reportée au 20 mars]':'http://soufflebleu.fr/2013/03/09/universite-popualire-jazz-mercredi-13-mars-2013/',
'[Histoires de chansons françaises.]':'http://soufflebleu.fr/2013/03/06/histoires-de-chansons-francaises/',
'[A travers les nouveautés jazz…]':'http://soufflebleu.fr/2013/03/06/a-travers-les-nouveautes-jazz/',
'[Rendez-vous de la semaine.]':'http://soufflebleu.fr/2013/02/19/rendez-vous-de-la-semaine/',
'[Une réédition qui s’impose]':'http://soufflebleu.fr/2013/02/17/une-reedition-qui-simpose/',
'[Nouveautés jazz janvier 2013]':'http://soufflebleu.fr/2013/02/05/nouveautes-jazz-janvier-2013/',
'[Du côté des nouveautés en jazz]':'http://soufflebleu.fr/2012/12/12/du-cote-des-nouveautes-en-jazz/',
'[Le saxophone dans deux états]':'http://soufflebleu.fr/2012/11/27/le-saxophone-dans-deux-etats/',
'[Jazz, des coffrets nécessaires.]':'http://soufflebleu.fr/2012/11/27/jazz-des-coffrets-necessaires/',
'[Nouveautés jazz, rentrée 2012 (2)]':'http://soufflebleu.fr/2012/10/17/nouveautes-jazz-rentee-2012-2/',
'[Des nouvelles du jazz, rentrée 2012]':'http://soufflebleu.fr/2012/10/14/des-nouvelles-du-jazz-rentree-2012/',
'[Conserver notre patrimoine]':'http://soufflebleu.fr/2012/10/10/conserver-notre-patrimoine/',
'[Une exposition à la Cité de la Musique, un catalogue et un coffret de cinq CD, actualité de Django Reinhardt pour le 60e anniversaire de sa mort le 16 mai 1953. Il avait 43 ans.]':'http://soufflebleu.fr/2012/10/04/une-exposition-a-la-cite-de-la-musique-un-catalogue-et-un-coffret-de-cinq-cd-actualite-de-django-reinhardt-pour-le-60e-anniversaire-de-sa-mort-le-16-mai-1953-il-avait-43-ans/',
'[A propos du jazz en France, retour sur des concepts]':'http://soufflebleu.fr/2012/09/09/a-propos-du-jazz-en-france-retour-sur-des-concepts/',
'[Chroniques de disques de jazz]':'http://soufflebleu.fr/2012/07/16/267/',
'[A propos de Miles et de Solar]':'http://soufflebleu.fr/2012/07/10/a-propos-de-miles-et-de-solar/',
'[Un jazz, des jazz ?]':'http://soufflebleu.fr/2012/07/05/un-jazz-des-jazz/',
'[Jazz, économie : un endroit pour s’exprimer]':'http://soufflebleu.fr/2012/06/11/5/',
'[Réflexions sur le jazz]':'http://soufflebleu.fr/2012/05/05/reflexions-sur-le-jazz/',
'[Petit voyage à travers quelques nouveautés en jazz, décembre 2011]':'http://soufflebleu.fr/2011/12/11/petit-voyage-a-travers-quelques-nouveautes-en-jazz-decembre-2011/',
'[TOUT AUTOUR DU PIANO.]':'http://soufflebleu.fr/2011/11/25/tout-autour-du-piano/',
'[Pour voyager léger…]':'http://soufflebleu.fr/2011/11/25/pour-voyager-leger/',
'[Nouveautés jazz novembre 2011]':'http://soufflebleu.fr/2011/11/25/nouveautes-jazz-novembre-2011/',
'[Les Israéliens et le jazz de New York.]':'http://soufflebleu.fr/2011/11/25/les-israeliens-et-le-jazz-de-new-york/',
'[Un tromboniste, Samuel Blaser]':'http://soufflebleu.fr/2011/10/25/un-tromboniste-samuel-blaser/',
'[Deux démiurges du jazz]':'http://soufflebleu.fr/2011/10/25/deux-demiurges-du-jazz/',
'[Des mots et des musiques oubliées]':'http://soufflebleu.fr/2011/10/25/des-mots-et-des-musiques-oubliees/',
'[Au fil du jazz]':'http://soufflebleu.fr/2011/10/25/au-fil-du-jazz/',
'[Anthropologie ?]':'http://soufflebleu.fr/2010/08/22/anthropologie/',
'[femmes dans le jazz]':'http://soufflebleu.fr/2010/07/05/femmes-dans-le-jazz/',
'[Pour Django]':'http://soufflebleu.fr/2008/07/05/pour-django/',
'[Bibliographie, à propos de jazz]':'http://soufflebleu.fr/2005/07/05/bibliographie-a-propos-de-jazz/',
'[Trajectoires de Django Reinhardt]':'http://soufflebleu.fr/2003/07/10/trajectoires-de-django-reinhardt/',
'[A propos de la musique et de la littérature cubaines.]':'http://soufflebleu.fr/2001/05/13/a-propos-de-la-musique-et-de-la-litterature-cubaines/',
'[Réflexions sur le 21e siècle]':'http://soufflebleu.fr/2000/11/17/reflexions-sur-le-21e-siecle/',
'[Interrogations sur le jazz et l’art du 21e siècle]':'http://soufflebleu.fr/2000/11/12/interrogations-sur-le-jazz-et-lart-du-21e-siecle/',
'[A Jeanne Lee]':'http://soufflebleu.fr/2000/10/29/a-jeanne-lee/',
'[Sur le livre de Jalard : Le jazz est‑il encore possible ?]':'http://soufflebleu.fr/2000/08/10/sur-le-livre-de-jalard-le-jazz-est%e2%80%91il-encore-possible/',
'[A propos de la critique de jazz]':'http://soufflebleu.fr/2000/08/10/a-propos-de-la-critique-de-jazz/',
'[Avec Jacques Prévert…]':'http://soufflebleu.fr/2000/03/13/avec-jacques-prevert/',
'[Chronique de disques de février 2000]':'http://soufflebleu.fr/2000/02/13/chronique-de-disques-de-fevrier-2000/',
'[Deux «dictionnaires » (publié dans la revue de l’Ecole Emancipée)]':'http://soufflebleu.fr/2000/01/10/deux-dictionnaires-publie-dans-la-revue-de-lecole-emancipee/',
'[Travail de mémoire]':'http://soufflebleu.fr/2000/01/03/travail-de-memoire/',
'[Pour Art Farmer et Milt Jackson]':'http://soufflebleu.fr/1999/10/25/pour-art-farmer-et-milt-jackson/',
'[Exception culturelle ?]':'http://soufflebleu.fr/1999/10/12/exception-culturelle/',
'[Quand la littérature se fait mémoire…(Publié dans Nouveaux regards)]':'http://soufflebleu.fr/1999/09/30/quand-la-litterature-se-fait-memoire-publie-dans-nouveaux-regards/',
'[Jazz, du neuf en 1998]':'http://soufflebleu.fr/1999/08/10/jazz-du-neuf-en-1998/',
'[Billie, pour toujours.]':'http://soufflebleu.fr/1999/07/09/billie-pour-aloue/',
'[Nouveautés en jazz de 1999]':'http://soufflebleu.fr/1999/06/14/nouveautes-en-jazz-de-1999/',
'[A Boris Vian et au jazz (article publié dans Critique Communiste)]':'http://soufflebleu.fr/1999/05/31/a-boris-vian-et-au-jazz-article-publie-dans-critique-communiste/',
'[A Boris Vian]':'http://soufflebleu.fr/1999/05/31/a-boris-vian/',
'[Pour les 100 ans du Duke]':'http://soufflebleu.fr/1999/05/16/pour-les-100-ans-du-duke/',
'[Histoires du jazz]':'http://soufflebleu.fr/1999/02/28/histoires-du-jazz-publie-dans-la-revue-de-lecole-emancipee/',
'[Nouveautés jazz février 1999]':'http://soufflebleu.fr/1999/02/22/nouveautes-jazz-fevrier-1999/',
'[JAZZ]':'http://soufflebleu.fr/1999/01/10/jazz-publie-dans-la-revue-de-lecole-emancipee/',
'[Michel Petrucciani, un homme pressé.]':'http://soufflebleu.fr/1999/01/07/michel-petrucciani-un-homme-presse/',
'[JAZZ, retour qsur les années révolution, première partie]':'http://soufflebleu.fr/1998/11/25/jazz-retour-qsur-les-annees-revolution-premiere-partie-publie-dans-la-revue-de-lecole-emancipee/',
'[Un roman sur la culture américaine…]':'http://soufflebleu.fr/1998/08/18/un-roman-sur-la-culture-americaine/',
'[Le jazz et la France]':'http://soufflebleu.fr/1998/08/18/le-jazz-et-la-france/',
}

class articles:

	def init_articlesDB(self):
		articles.DB = []
		articles.DB = nbenies_title_url_dict
		return articles.DB
